### ISSUE TITLE
REQUEST: New membership for <li-jin-gou>

### ISSUE THREAD

**Issue by li-jin-gou** [cloudwego/community#10]
### GitHub Username

li-jin-gou

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/cloudwego/community/blob/master/community-membership.md)
- [x] I have joined to the [Slack Channel](https://join.slack.com/t/cloudwego/shared_invite/zt-tmcbzewn-UjXMF3ZQsPhl7W3tEDZboA) and Feishu Group Chat (for Chinese)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more CloudWeGo repositories

### List of contributions to CloudWeGo

- PRs reviewed / authored
   -  https://github.com/cloudwego/kitex-examples/pull/22
   -  https://github.com/kitex-contrib/registry-eureka/pull/3
   - https://github.com/kitex-contrib/registry-polaris/pull/2
   -  https://github.com/cloudwego/kitex/pull/344
   -  https://github.com/cloudwego/kitex/pull/317

**Comment by Hchenn** [comment]
+1

**Comment by simon0-o** [comment]
+1

**Comment by GuangmingLuo** [comment]
@li-jin-gou  participates in the CloudWeGo community actively including the new extension of registry, new business demo for kitex-example,  code reviewing and issue discussion. I agree with this request.

**Comment by GuangmingLuo** [comment]
Hi, your request has been reviewed by the project management team and passed with a comfortable majority. Congratulations !

You have been invited to join [CloudWeGo](https://github.com/cloudwego) and [kitex-contrib](https://github.com/kitex-contrib) orgs as public members.

Your certificate for being a member of our community is [here](https://github.com/cloudwego/community/blob/main/Committer/li-jin-gou.pdf).

Welcome to Join us !
