### ISSUE TITLE
REQUEST: New membership for <CoderPoet>

### ISSUE THREAD

**Issue by CoderPoet** [cloudwego/community#17]
### GitHub Username
CoderPoet

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md)
- [x] I have joined to the [Slack Channel](https://join.slack.com/t/cloudwego/shared_invite/zt-tmcbzewn-UjXMF3ZQsPhl7W3tEDZboA) and Feishu Group Chat (for Chinese)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more CloudWeGo repositories

### List of contributions to CloudWeGo

- PRs reviewed / authored
   - https://github.com/kitex-contrib/obs-opentelemetry/pull/1
   - https://github.com/cloudwego/kitex-examples/pull/26

**Comment by GuangmingLuo** [comment]
@CoderPoet  participates in the CloudWeGo community actively including the new integration of opentelemetry, new demo for opentelemetry integration. I agree with this request.

**Comment by YangruiEmma** [comment]
I strongly support @CoderPoet joining CloudWeGo community. Thank you for your contribution! Welcome!

**Comment by PureWhiteWu** [comment]
I support @CoderPoet joining CloudWeGo community. Thank you for your contribution! Welcome!

**Comment by simon0-o** [comment]
I strongly support @CoderPoet joining CloudWeGo community. Thank you for your contribution! Welcome!

**Comment by ppzqh** [comment]
I agree with this request. Thanks for @CoderPoet 's contribution to the community. So glad you can join the CloudWego community. Welcome!

**Comment by GuangmingLuo** [comment]
Hi, your request has been reviewed by the project management team and passed with a comfortable majority. Congratulations !

You have been invited to join [CloudWeGo](https://github.com/cloudwego) and [kitex-contrib](https://github.com/kitex-contrib) orgs as public members.

Your certificate for being a member of our community is [here](https://github.com/cloudwego/community/blob/main/Committer/CoderPoet.pdf).

Welcome to Join us !
