### ISSUE TITLE
[CSG第一期]  kitex 源码解析学习活动

### ISSUE THREAD

**Issue by cloudwegoIce** [cloudwego/community#24]
>### 🌟CloudWeGo Study Group （CSG） 简单介绍
> 👏**欢迎大家来到 CSG** ！🎉
>
> 随着 Golang 逐渐成为云原生时代大量应用的编程语言，基于 Golang 的微服务中间件在开源社区有着越来越大的诉求。自CloudWeGo 开源以来，项目从社区中获得了非常有效的支持，同时，我们也接受到一些开发者开发者的声音，希望能够有更多和社区核心开发者进行实际互动的机会，来了解架构设计的思路和核心理念。
>
> 因此成立了CloudWeGo Study Group（CSG），开展以30天为周期的源码解析活动，互相分享自己的学习笔记，给更多感兴趣，想要入门的同学一个学习的平台。

### 活动内容

对CloudWeGo kiteX 进行技术点解析
kiteX： https://github.com/cloudwego/kitex
版本：V0.3.0

|活动参与时间| 5.19-6.30  |
|------------|---|
|优秀参与者评选|  6.30-7.10  |
|优秀参与者公布|  7.11-7.15    |

### 😊  参与会获得什么
1.  一份由CloudWeGo    **📑社区整理的RPC学习资料**。从初级快速进阶，体会架构师的设计之思。
2. 完成学习笔记打卡的同学即可获得  **🏅CSG积分，获得 CSG 成员证书**、周边礼包，优秀者有机会获得字节跳动实习内推和社招内推机会！
3. 一个自律的学习小组，study group 里有项目导师和社区contributor 全程跟进， **👩🏼‍🎓和项目导师直接进行交流学习**

**我们会根据笔记积分，评选优秀成员额外颁发 CSG 活动奖品**，并会获得项目曝光，展示在优秀CSG成员页中：

| 奖项 | ⭐️1 等奖 （3名）  | 🌟2 等奖（5名）  | ✨3 等奖 （8名）  |
|----|---|---|---|
| 奖品 | CSG证书 + CSG 学习礼包 + CloudWeGo 周边礼包  | CSG证书+ 学习书籍 + CloudWeGo 周边礼包  | CloudWeGo 周边礼包  |

### 💻  参与方式

1. 完成报名，加入学习小组群。
> 报名链接：https://www.wjx.top/vj/OJwnYAc.aspx
2. 选择 **课题模块** 内容进行学习，并产出学习笔记
> 学习资料：https://cloudwego.feishu.cn/docs/doccnyu0JEq4DiKwuKATn3MxIOf
3. 发布学习笔记，可选择发布至oschina,掘金，csdn等各个社区或个人博客、公众号等各个渠道
> 小tips: 掘金有闪念笔记功能，可以边学边记
4. 提交笔记链接，提交入口: https://www.wjx.top/vj/miPxCNV.aspx
5. 每人可发布多个笔记，会根据笔记质量进行积分累加，量多质佳更加分

### 📜优秀参与者评选标准
CloudWeGo 项目组技术评审团会根据内容质量对每篇笔记进行打分，可发布多篇笔记，笔记数量和质量都是评选的维度

参考笔记解析思路：
- 代码设计现状、处理链路，横向对比其他开源项目 
- 优秀设计的好处或设计背景
- 如何扩展
- 常见问题解答
- 最佳实践

参考笔记：https://mp.weixin.qq.com/s/B9Y2Xq0GQSYc59qFgV6jiA

### 📑课题模块选择
- kitex 模块设计及调用链路
- 服务治理
  - 服务发现
  - 路由
  - 负载均衡
  - 超时控制
  - klog
  - config
  - kerrors
  - acl
  - circuitbreak 熔断器
  - connpool
  - event
  - stats
- 框架公共模块
  - rpcinfo
  - endpoint
    - middleware，mw 的实现和各处用法？
- remote 模块，与远端通信
  - transport pipeline
    - bound
      - 服务端限流
      - 元信息透传
  - trans handler
    -  client 处理
    -  server 处理
  - 编解码协议
    - codec，例：如何做协议探测？
    - payloadCodec，例：怎么扩展自己的协议？
- kitex tool
  - cmd
  - generator

**Comment by lunaadeng** [comment]
uu们，最近刚p了一套 cloudwego 头像😂  快来找我拿～

**Comment by PotatochipsHub** [comment]
微信号搜着说暂时违规不能被添加好友

**Comment by cloudwegoIce** [comment]
> 微信号搜着说暂时违规不能被添加好友

🥹🥹刚被告知，被微信封号了。。。离了大谱

**Comment by cloudwegoIce** [comment]
> 微信号搜着说暂时违规不能被添加好友

🥹🥹刚被告知，被微信封号了。。。离了大谱
请添加这个账号：1515019109

**Comment by cloudwegoIce** [comment]
第一期 CSG 源码解读活动已经正式结束啦～  

**🎉 获得 CSG MEMBER 成员证书 开发者：** 


**- 白泽z  （俞聪）**
笔记链接：
- [ ] Kitex源码阅读——脚手架代码是如何通过命令行生成的(一) 链接：https://juejin.cn/post/7100867939829563422
- [ ] Kitex源码阅读——脚手架代码是如何通过命令行生成的(二)  链接：https://juejin.cn/post/7102386530869575717
- [ ] 使用Kitex框架构建自己的服务｜链接：https://juejin.cn/post/7098966260502921230
- [ ] Go日志库log竟然这么小巧！链接：https://juejin.cn/post/7103790667595268126
- [ ] 字节RPC框架Kitex的日志库klog竟然也这么小巧！链接：https://juejin.cn/post/7104825435795980324
- [ ] rpc的正确打开方式｜读懂Go原生net/rpc包   链接：https://juejin.cn/post/7107623772982607886


![白泽](https://user-images.githubusercontent.com/104130938/178220409-41b96e32-58d2-4d42-929e-6d0cb90230df.jpg)

**- skyenought （李纪昀）**

- [ ] 对于 CloudWeGo kitex 生成工具的源码分析    链接： https://juejin.cn/post/7099863782767198239
- [ ] Kitex源码阅读——脚手架代码是如何通过命令行生成的(一)  链接：https://juejin.cn/post/7100867939829563422
- [ ] Kitex 源码解析 —— 将服务注册进入注册中心的细节  链接： https://juejin.cn/post/7102501824220889119

![李纪昀](https://user-images.githubusercontent.com/104130938/178220566-f9723024-b413-46d6-8353-372423a3b0a4.jpg)


> 以下成员（和白泽z  （俞聪）、skyenought （李纪昀））共同参与编写1.6w字 [《Kitex前传：RPC你不得不知道的故事》](https://cloudwego.feishu.cn/docs/doccnSvZ2NZJomRljYWAJG3hCWd)


**- Addicated**
![addicated](https://user-images.githubusercontent.com/104130938/178220597-87240d0e-bf81-4fe3-894f-854d6a0d27ff.jpg)

**- Xxx**
![xxx](https://user-images.githubusercontent.com/104130938/178220631-3bfffd18-8659-471b-a5a5-1d1554e2a72a.jpg)

**- 黄小龙**
![huangxiaolong](https://user-images.githubusercontent.com/104130938/178220694-599912f8-cc3b-417e-b06d-1d67dabb22cc.jpg)

**- Jacob953  （余俊锋）**
![junfeng](https://user-images.githubusercontent.com/104130938/178220752-4a8f5bdb-37c3-4eb9-8325-db0d44c8f64b.jpg)
