### ISSUE TITLE
Update more infomations about "Community Meeting"

### ISSUE THREAD

**Issue by STRRL** [cloudwego/community#27]
I heard from social media that CloudWeGo Community would hold bi-weekly community meetings 

But I failed to find more descriptions and links about that. Eg. https://github.com/cloudwego/community#community-meetings

Maybe we could update more information about that?

**Comment by GuangmingLuo** [comment]
Hello, welcome to join us. 

Currently, the community meetings open to contributors and to-be-contributors only. Please join our Feishu User Group and reach out to me so that I can add you to the developer group and meeting agenda.
