### ISSUE TITLE
REQUEST: New membership for horizonzy

### ISSUE THREAD

**Issue by horizonzy** [cloudwego/community#3]
### GitHub Username
horizonzy

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/cloudwego/community/blob/master/community-membership.md)
- [x] I have joined to the [Slack Channel](https://join.slack.com/t/cloudwego/shared_invite/zt-tmcbzewn-UjXMF3ZQsPhl7W3tEDZboA) and Feishu Group Chat (for Chinese)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more CloudWeGo repositories

### List of contributions to CloudWeGo

- https://github.com/kitex-contrib/registry-zookeeper/pull/1
- https://github.com/cloudwego/kitex/pull/132

**Comment by YangruiEmma** [comment]
+1

**Comment by simon0-o** [comment]
+1

**Comment by GuangmingLuo** [comment]
Hi, your request has been reviewed by the project management team and passed with a comfortable majority. Congratulations !

**Comment by GuangmingLuo** [comment]
Member has been added to the CloudWeGo Organization, This issue is done !
