### ISSUE TITLE
REQUEST: New membership for <Skyenought>

### ISSUE THREAD

**Issue by Skyenought** [cloudwego/community#35]
### GitHub Username

Skyenought

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md)
- [x] I have joined to the [Slack Channel](https://join.slack.com/t/cloudwego/shared_invite/zt-tmcbzewn-UjXMF3ZQsPhl7W3tEDZboA) and Feishu Group Chat (for Chinese)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more CloudWeGo repositories

### List of contributions to CloudWeGo

- PRs reviewed / authored
  - Translate Docs
    - [docs(readme) add README_CN.md [cloudwego/hertz-examples]](https://github.com/cloudwego/hertz-examples/pull/3)
    - [docs: translate hertz/tutorials/basic-feature/stream [cloudwego/cloudwego.github.io]](https://github.com/cloudwego/cloudwego.github.io/pull/210)
    - [docs: translate hertz/tutorials/basic-feature/bindAndValidate and fix markdown syntax error in zh docs [cloudwego/cloudwego.github.io]](https://github.com/cloudwego/cloudwego.github.io/pull/216)
    - [docs: translate hertz/tutorials/framework-exten/advanced-exten/protocol [cloudwego/cloudwego.github.io]](https://github.com/cloudwego/cloudwego.github.io/pull/224)
    - [docs: translate hertz/tutorials/basic-feature/stream [cloudwego/cloudwego.github.io]](https://github.com/cloudwego/cloudwego.github.io/pull/210)
    - [docs: translate hertz/tutorials/basic-feature/bindAndValidate and fix markdown syntax error in zh docs [cloudwego/cloudwego.github.io]](https://github.com/cloudwego/cloudwego.github.io/pull/216)
    - [docs: translate hertz/tutorials/framework-exten/advanced-exten/protocol [cloudwego/cloudwego.github.io]](https://github.com/cloudwego/cloudwego.github.io/pull/224)
  - Code Contribution
    - [style: fix typo (tempalte -> template) [cloudwego/hertz-examples]](https://github.com/cloudwego/hertz-examples/pull/12)
    - [feat: add multiple_service example [cloudwego/hertz-examples]](https://github.com/cloudwego/hertz-examples/pull/21)
    - [feat: add sentinel example [cloudwego/kitex-examples]](https://github.com/cloudwego/kitex-examples/pull/41)
    - [feat: add sentinel example [cloudwego/hertz-examples]](https://github.com/cloudwego/hertz-examples/pull/28)
    - [feat: add sentinel adapter [hertz-contrib/opensergo]](https://github.com/hertz-contrib/opensergo/pull/1)
    - [refactor: package [hertz-contrib/opensergo]](https://github.com/hertz-contrib/opensergo/pull/2)
    - [feat: add adapter for hertz [alibaba/sentinel-golang]](https://github.com/alibaba/sentinel-golang/pull/472)
    - [optimize: remove useless judgement [cloudwego/hertz]](https://github.com/cloudwego/hertz/pull/128)
    - [refactor: rebuild zh community page [cloudwego/cloudwego.github.io]](https://github.com/cloudwego/cloudwego.github.io/pull/196)
    - [docs(FAQ): add questions about kitex generator tool [cloudwego/cloudwego.github.io]](https://github.com/cloudwego/cloudwego.github.io/pull/197)
    - [Author of [hertz-contrib/i18n]](https://github.com/hertz-contrib/i18n)
    - [Author of [hertz-contrib/gzip]](https://github.com/hertz-contrib/gzip)
    - [Author of [hertz-contrib/sessions]](https://github.com/hertz-contrib/sessions)
    - [Author of [hertz-contrib/registry/nacos]](https://github.com/hertz-contrib/registry)
- Issues about CloudWeGo
  - [Proposal: add a flag to support custom suffixes for IDL [cloudwego/hertz]](https://github.com/cloudwego/hertz/issues/135)
  - [Proposal: generate tool about cloudwego [cloudwego/kitex]](https://github.com/cloudwego/kitex/issues/531)
- Code Review of CloudWeGo
  - [feat: Support Hertz to use Consul for service discovery and registration](https://github.com/hertz-contrib/registry/pull/8)
  - [feat: support service registeration and discovery with Netflix Eureka](https://github.com/hertz-contrib/registry/pull/16)
  - [feat: add etcd registry](https://github.com/hertz-contrib/registry/pull/14)
  - [feat: add zookeeper register](https://github.com/hertz-contrib/registry/pull/6)
- Articles about CloudWeGo
1. [对于 CloudWeGo kitex 生成工具的源码分析](https://juejin.cn/post/7099863782767198239) 
2. [Kitex Tool 解析第二期 —— 文件是怎么自动生成的](https://juejin.cn/post/7101618834376753165)
3. [Kitex 源码解析 —— 将服务注册进入注册中心的细节](https://juejin.cn/post/7102501824220889119)
4. [Hertz 源码解析—— hz new 是怎么生成代码文件的](https://juejin.cn/post/7119465480997306376)
5. [Hertz 源码解析—— hz 是怎么支持自定义模板功能的？](https://juejin.cn/post/7119918455796531236)
6. [Hertz 源码解析 —— 对 hz 工具的小改动](https://juejin.cn/post/7123064526794129439) 
7. [Hertz 和 Sentinel Go 的对接方案](https://sentinelguard.io/zh-cn/blog/sentinel-golang-and-cloudwego-hertz.html)

**Comment by li-jin-gou** [comment]
+1

**Comment by Duslia** [comment]
+1

**Comment by GuangmingLuo** [comment]
+1

**Comment by cloudwegoIce** [comment]
+1 👍

**Comment by welkeyever** [comment]
thanks a lot, approve

**Comment by PureWhiteWu** [comment]
+1

**Comment by FGYFFFF** [comment]
+1 ❤️

**Comment by GuangmingLuo** [comment]
Hi, your request has been reviewed by the CloudWeGo-Hertz project management team and passed with unanimous approval. Congratulations !

You have been invited to join [CloudWeGo](https://github.com/cloudwego) and [hertz-contrib](https://github.com/hertz-contrib) orgs as public members, as well as Hertz-committers team in CloudWeGo.

Please check [Responsibilities and privileges](https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md#responsibilities-and-privileges-1) for more details.

Welcome to Join us !

**Comment by GuangmingLuo** [comment]
Your certificate is [here](https://github.com/cloudwego/community/blob/main/Committer/skyenought.pdf).
