### ISSUE TITLE
REQUEST: New membership for <rogerogers>

### ISSUE THREAD

**Issue by rogerogers** [cloudwego/community#42]
### GitHub Username

rogerogers

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md)
- [x] I have joined to the [Slack Channel](https://join.slack.com/t/cloudwego/shared_invite/zt-tmcbzewn-UjXMF3ZQsPhl7W3tEDZboA) and Feishu Group Chat (for Chinese)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more CloudWeGo repositories

### List of contributions to CloudWeGo

- PRs reviewed / authored

  - docs

    - https://github.com/cloudwego/cloudwego.github.io/pull/254
    - https://github.com/cloudwego/cloudwego.github.io/pull/255
    - https://github.com/cloudwego/cloudwego.github.io/pull/258
    - https://github.com/cloudwego/cloudwego.github.io/pull/263
    - https://github.com/cloudwego/cloudwego.github.io/pull/273
    - https://github.com/cloudwego/cloudwego.github.io/pull/301
    - https://github.com/cloudwego/cloudwego.github.io/pull/303
    - https://github.com/cloudwego/cloudwego.github.io/pull/319
    - https://github.com/cloudwego/cloudwego.github.io/pull/331
    - https://github.com/cloudwego/cloudwego.github.io/pull/340
    - https://github.com/cloudwego/cloudwego.github.io/pull/356
    - https://github.com/cloudwego/cloudwego.github.io/pull/375

  - hertz

    - https://github.com/hertz-contrib/registry/pull/9
    - https://github.com/hertz-contrib/monitor-prometheus/pull/1
    - https://github.com/hertz-contrib/monitor-prometheus/pull/2
    - https://github.com/hertz-contrib/obs-opentelemetry/pull/8
    - https://github.com/cloudwego/hertz/pull/267
    - https://github.com/cloudwego/hertz-examples/pull/34
    - https://github.com/hertz-contrib/obs-opentelemetry/pull/10
    - https://github.com/hertz-contrib/monitor-prometheus/pull/4

  - kitex

    - https://github.com/kitex-contrib/obs-opentelemetry/pull/10
    - https://github.com/kitex-contrib/obs-opentelemetry/pull/11
    - https://github.com/cloudwego/kitex-examples/pull/44
    - https://github.com/kitex-contrib/obs-opentelemetry/pull/13
    - https://github.com/cloudwego/kitex-examples/pull/43
    - https://github.com/kitex-contrib/monitor-prometheus/pull/9

- Issues responded to
    - https://github.com/kitex-contrib/obs-opentelemetry/issues/7
    - https://github.com/cloudwego/hertz/issues/212
    - https://github.com/hertz-contrib/monitor-prometheus/issues/3
    - https://github.com/kitex-contrib/monitor-prometheus/issues/8

**Comment by GuangmingLuo** [comment]
+1 Binding for  「Website & Docs」 Committer Team

**Comment by welkeyever** [comment]
+1 thx a lot & welcome!

**Comment by cloudwegoIce** [comment]
+1   🎉🎉🎉

**Comment by li-jin-gou** [comment]
+1 :heart: :heart:

**Comment by YangruiEmma** [comment]
+1 🎉

**Comment by Skyenought** [comment]
+1

**Comment by GuangmingLuo** [comment]
Hi, your request has been reviewed by the CloudWeGo community management team and passed with majority approval. Congratulations !

You have been invited to join [CloudWeGo](https://github.com/cloudwego) org as a public member, as well as Website & Docs Committer Team in CloudWeGo.

Please check [Responsibilities and privileges](https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md#responsibilities-and-privileges-1) for more details.

Welcome to Join us !

**Comment by GuangmingLuo** [comment]
Your certificate is [here](https://github.com/cloudwego/community/blob/main/Committer/rogerogers.pdf)
