### ISSUE TITLE
REQUEST: New membership for <BaiZe1998>

### ISSUE THREAD

**Issue by BaiZe1998** [cloudwego/community#48]
### GitHub Username

BaiZe1998

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md)
- [x] I have joined to the [Slack Channel](https://join.slack.com/t/cloudwego/shared_invite/zt-tmcbzewn-UjXMF3ZQsPhl7W3tEDZboA) and Feishu Group Chat (for Chinese)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more CloudWeGo repositories

### List of contributions to CloudWeGo

- Docs for Hertz
    - https://github.com/cloudwego/cloudwego.github.io/pull/276
    - https://github.com/cloudwego/cloudwego.github.io/pull/388
    - https://github.com/cloudwego/cloudwego.github.io/pull/369
    - https://github.com/cloudwego/cloudwego.github.io/pull/391
    - https://github.com/cloudwego/cloudwego.github.io/pull/396
    - https://github.com/cloudwego/cloudwego.github.io/pull/437
    - https://github.com/cloudwego/cloudwego.github.io/pull/441
    - https://github.com/cloudwego/cloudwego.github.io/pull/453
- Feature
    - https://github.com/cloudwego/hertz/pull/251
    - https://github.com/cloudwego/hertz/pull/258
    - https://github.com/cloudwego/hertz/pull/271
    - https://github.com/cloudwego/hertz/pull/285
    - https://github.com/cloudwego/hertz/pull/304
    - https://github.com/hertz-contrib/jwt/pull/7
    - https://github.com/hertz-contrib/jwt/pull/9
    - https://github.com/cloudwego/kitex-examples/pull/49
    - https://github.com/cloudwego/hertz-examples/pull/49
    - https://github.com/cloudwego/hertz/pull/401
- Issues
    - https://github.com/cloudwego/hertz/issues/319
    - https://github.com/cloudwego/hertz/issues/161
- Review
    - https://github.com/cloudwego/cloudwego.github.io/pull/382
    - https://github.com/cloudwego/cloudwego.github.io/pull/389
    - https://github.com/cloudwego/cloudwego.github.io/pull/380
    - https://github.com/cloudwego/cloudwego.github.io/pull/379
    - https://github.com/cloudwego/cloudwego.github.io/pull/381
- Article
    - [Kitex前传：RPC框架那些你不得不知的故事](https://cloudwego.feishu.cn/docs/doccnSvZ2NZJomRljYWAJG3hCWd)
    - [Kitex源码阅读——脚手架代码是如何通过命令行生成的(一)](https://juejin.cn/post/7100867939829563422)
    - [Kitex源码阅读——脚手架代码是如何通过命令行生成的(二)](https://juejin.cn/post/7102386530869575717)
    - [字节RPC框架Kitex的日志库klog竟然也这么小巧！](https://juejin.cn/post/7104825435795980324)
    - [字节微服务HTTP框架Hertz使用与源码分析｜拥抱开源](https://juejin.cn/post/7138416105583804430)
    - [Source Code Analysis for Go HTTP Framework Hertz](https://dev.to/baize1998/source-code-analysis-for-go-http-framework-hertz-4jgi)
    - [Web Development JWT Practices](https://dev.to/baize1998/web-development-jwt-practices-59cn)

**Comment by li-jin-gou** [comment]
Need more contribution to become a Hertz Committer, fighting and I am looking forward to it. :)

**Comment by welkeyever** [comment]
+1, welcome🤗

**Comment by li-jin-gou** [comment]
+1, look forward to your further contributions to Hertz ❤️

**Comment by justlorain** [comment]
+1, welcome, learned a lot from you❤️

**Comment by GuangmingLuo** [comment]
+1, Welcome ~

**Comment by Duslia** [comment]
+1

**Comment by rogerogers** [comment]
+1

**Comment by baiyutang** [comment]
+1

**Comment by cloudwegoIce** [comment]
👏👏

**Comment by L2ncE** [comment]
+1, thanks for ur contribution. And the article is very good.

**Comment by BaiZe1998** [comment]
Thank you all and I will continue to contribute to the community in the future :-)
