### ISSUE TITLE
REQUEST: New membership for <liu-song>

### ISSUE THREAD

**Issue by liu-song** [cloudwego/community#5]
### GitHub Username
liu-song 

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/cloudwego/community/blob/master/community-membership.md)
- [x] I have joined to the [Slack Channel](https://join.slack.com/t/cloudwego/shared_invite/zt-tmcbzewn-UjXMF3ZQsPhl7W3tEDZboA) and Feishu Group Chat (for Chinese)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more CloudWeGo repositories

### List of contributions to CloudWeGo

- PRs reviewed / authored
  - https://github.com/kitex-contrib/registry-polaris/pull/1
  - https://github.com/cloudwego/netpoll/pull/59
  - https://github.com/cloudwego/kitex/pull/186
  - https://github.com/cloudwego/kitex/pull/203
  - https://github.com/cloudwego/kitex/pull/230
  - https://github.com/cloudwego/kitex/pull/304
- Issues responded to
  - https://github.com/cloudwego/kitex/issues/192
  - https://github.com/cloudwego/kitex/issues/218
  - https://github.com/cloudwego/netpoll/issues/57
- discussions
  - https://github.com/cloudwego/kitex/discussions/306

**Comment by YangruiEmma** [comment]
Song participates in CloudWeGo community actively includes the new extension of registry, optimization, and discussion. I agree with this request. ; )

**Comment by Hchenn** [comment]
+1

**Comment by SinnerA** [comment]
+1

**Comment by lsjbd** [comment]
+1

**Comment by GuangmingLuo** [comment]
Hi, your request has been reviewed by the project management team and passed with a comfortable majority. Congratulations !

**Comment by GuangmingLuo** [comment]
You have been invited to join CloudWeGo and kitex-contrib orgs as public members.

**Comment by GuangmingLuo** [comment]
@liu-song Your certificate for being a member of our community is here: https://github.com/cloudwego/community/blob/main/Committer/liu-song.pdf
Welcome to Join us !
