### ISSUE TITLE
REQUEST: New membership for <justlorain>

### ISSUE THREAD

**Issue by justlorain** [cloudwego/community#51]
### GitHub Username

justlorain

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md)
- [x] I have joined to the [Slack Channel](https://join.slack.com/t/cloudwego/shared_invite/zt-tmcbzewn-UjXMF3ZQsPhl7W3tEDZboA) and Feishu Group Chat (for Chinese)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more CloudWeGo repositories

### List of contributions to CloudWeGo
**Hertz**:
- Doc
  - https://github.com/cloudwego/cloudwego.github.io/pull/304
  - https://github.com/cloudwego/cloudwego.github.io/pull/341
  - https://github.com/cloudwego/cloudwego.github.io/pull/351
  - https://github.com/cloudwego/cloudwego.github.io/pull/379
  - https://github.com/cloudwego/cloudwego.github.io/pull/380
  - https://github.com/cloudwego/hertz-examples/pull/46
  - https://github.com/cloudwego/cloudwego.github.io/pull/381
  - https://github.com/hertz-contrib/logger/pull/11
- Feature
  - https://github.com/cloudwego/hertz/pull/273
  - https://github.com/hertz-contrib/requestid/pull/5
  - https://github.com/cloudwego/hertz-examples/pull/47
  - https://github.com/hertz-contrib/registry/pull/24
  - https://github.com/cloudwego/hertz/pull/366
  - https://github.com/hertz-contrib/requestid/pull/4
  - https://github.com/kitex-contrib/registry-nacos/pull/16
  - https://github.com/hertz-contrib/requestid/pull/8
- Review
  - https://github.com/cloudwego/cloudwego.github.io/pull/382
  - https://github.com/cloudwego/cloudwego.github.io/pull/396
  - https://github.com/cloudwego/cloudwego.github.io/pull/369
- Issue
  - https://github.com/hertz-contrib/requestid/issues/3
  - https://github.com/cloudwego/biz-demo/issues/11
  - https://github.com/hertz-contrib/registry/issues/23
  - https://github.com/cloudwego/hertz/issues/301
- Article
  - https://dev.to/justlorain/high-performance-go-http-framework-tasting-25li
  - https://dev.to/justlorain/high-performance-web-framework-tasting-database-operations-3m7

**Comment by li-jin-gou** [comment]
by the way your practical articles are excellent.❤️

**Comment by GuangmingLuo** [comment]
+1, I agree ! Excellent work in Hertz docs, blogs and code contribution in Hertz & Hertz-example & hertz-contrib/registry.

**Comment by li-jin-gou** [comment]
+1

**Comment by FGYFFFF** [comment]
+1

**Comment by L2ncE** [comment]
+1

**Comment by rogerogers** [comment]
+1

**Comment by Duslia** [comment]
+1

**Comment by GuangmingLuo** [comment]
Hi, your request has been reviewed by the CloudWeGo community management team and passed with majority approval. Congratulations !

You have been invited to join [CloudWeGo](https://github.com/cloudwego) org as a public member, as well as [Hertz](https://github.com/cloudwego/hertz) Committer Team in CloudWeGo. Your certificate is [here](https://github.com/cloudwego/community/blob/main/Committer/lorain.pdf).

Please check [Responsibilities and privileges](https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md#responsibilities-and-privileges-1) for more details.

Welcome to Join us !
