### ISSUE TITLE
REQUEST: New membership for <zstone12>

### ISSUE THREAD

**Issue by zstone12** [cloudwego/community#53]
### GitHub Username
zstone12
### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md)
- [x] I have joined to the [Slack Channel](https://join.slack.com/t/cloudwego/shared_invite/zt-tmcbzewn-UjXMF3ZQsPhl7W3tEDZboA) and Feishu Group Chat (for Chinese)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more CloudWeGo repositories

### List of contributions to CloudWeGo
- Doc Contribution
  - https://github.com/cloudwego/cloudwego.github.io/pull/382
  - https://github.com/cloudwego/cloudwego.github.io/pull/445
  - https://github.com/cloudwego/cloudwego.github.io/pull/402
  - https://github.com/cloudwego/cloudwego.github.io/pull/452
  - https://github.com/kitex-contrib/opensergo/pull/2
- Code Contribution
  - https://github.com/hertz-contrib/registry/pull/6
  - https://github.com/hertz-contrib/requestid/pull/7
  - https://github.com/kitex-contrib/opensergo/pull/3
  - https://github.com/cloudwego/hertz-examples/pull/53
  - https://github.com/kitex-contrib/obs-opentelemetry/pull/5
  - https://github.com/hertz-contrib/pprof/pull/3
  - https://github.com/cloudwego/hertz/pull/299
  - https://github.com/hertz-contrib/gzip/pull/4
- Code Review of CloudWeGo
  - https://github.com/hertz-contrib/keyauth/pull/1
  - https://github.com/hertz-contrib/registry/pull/24
  - https://github.com/hertz-contrib/registry/pull/8
  - https://github.com/hertz-contrib/secure/pull/1
  - https://github.com/cloudwego/cloudwego.github.io/pull/361
  - https://github.com/hertz-contrib/sessions/pull/2
- Issues about CloudWeGo
  - https://github.com/kitex-contrib/obs-opentelemetry/issues/4
  - https://github.com/cloudwego/hertz/issues/414

**Comment by li-jin-gou** [comment]
Thank you for your active contribution to the Hertz extension Code Review.❤️

**Comment by GuangmingLuo** [comment]
+1, thanks for your contribution.

**Comment by Duslia** [comment]
+1 Welcome~

**Comment by rogerogers** [comment]
+1, :thumbsup:

**Comment by L2ncE** [comment]
+1~

**Comment by welkeyever** [comment]
+1，Welcome~

**Comment by FGYFFFF** [comment]
+1，Welcome~

**Comment by li-jin-gou** [comment]
+1

**Comment by GuangmingLuo** [comment]
Hi, your request has been reviewed by the CloudWeGo community management team and passed with majority approval. Congratulations !

You have been invited to join [CloudWeGo](https://github.com/cloudwego) org and [hertz-contrib](https://github.com/hertz-contrib) as a public member, as well as [Hertz](https://github.com/cloudwego/hertz) Committer Team in CloudWeGo. Your certificate is [here](https://github.com/cloudwego/community/blob/main/Committer/zstone12.pdf).

Please check [Responsibilities and privileges](https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md#responsibilities-and-privileges-1) for more details.

Welcome to Join us !
