### ISSUE TITLE
REQUEST: New Reviewer for <baiyutang>

### ISSUE THREAD

**Issue by baiyutang** [cloudwego/community#54]
### GitHub Username

baiyutang

### Requirements

- [x] Committer for at least 1 month
- [x] Primary reviewer for at least 5 PRs to the codebase()
- [x] Reviewer for, or author of, at least 10 substantial PRs to the codebase, with the definition of substantial area to the maintainer's discretion (e.g. refactors/adds new functionality rather than one-line pulls)
- [x] Sponsored by a subproject maintainer
- [x] With no objections from other maintainers
- [x] May either self-nominate, be nominated by an maintainer in this subproject

### List of contributions to CloudWeGo
- [Committer for 11 months](https://github.com/cloudwego/community/issues/8)
- PRs reviewed
  - [kitex-contrib/registry-nacos (10)](https://github.com/kitex-contrib/registry-nacos/pulls?q=is%3Apr+is%3Amerged)
  - [kitex-contrib/registry-consul (1)](https://github.com/kitex-contrib/registry-consul/pull/4)
  - hertz-contrib/registry(2) 
    - https://github.com/hertz-contrib/registry/pull/7 
    - https://github.com/hertz-contrib/registry/pull/8
- PRs with new functionality 
  - kitex
    - https://github.com/cloudwego/kitex/pull/401
    - https://github.com/cloudwego/kitex/pull/581
  - [hertz-contrib/websocket](https://github.com/hertz-contrib/websocket)
  - kitex-examples
    - https://github.com/cloudwego/kitex-examples/pull/42 
   - biz-demo
     - https://github.com/cloudwego/biz-demo/pull/12
 - Other
     - [CloudWeGo 源码解读](https://github.com/baiyutang/cloudwego-read)
     - https://github.com/cloudwego/community/issues/24

**Comment by cloudwegoIce** [comment]
+1  🎉 🎉🎉

**Comment by YangruiEmma** [comment]
+1 ❤️ Thank you for @baiyutang's contributor!

**Comment by GuangmingLuo** [comment]
+1. Thanks for your contribution. You have showed your professionlism on the area of Service Resgistry and Project Engineering. We are looking forword to having you as a Reviewer of Kitex project and taking more responsibility as a core member of CloudWeGo community.

**Comment by baiyutang** [comment]
> +1. Thanks for your contribution. You have showed your professionlism on the area of Service Resgistry and Project Engineering. We are looking forword to having you as a Reviewer of Kitex project and taking more responsibility as a core member of CloudWeGo community.

Thanks for your affirmathion. I am proud of being member of you.

**Comment by PureWhiteWu** [comment]
+1 ❤️

**Comment by GuangmingLuo** [comment]
Hi, your request has been reviewed by the CloudWeGo community maintainer team and passed with majority approval. 

You have been promoted as a member of  [Kitex](https://github.com/cloudwego/kitex) Reviewer Team in CloudWeGo. Your certificate is [here](https://github.com/cloudwego/community/blob/main/Reviewer/baiyutang.pdf).

Please check [Responsibilities and privileges](https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md#responsibilities-and-privileges-2) for more details.

Congratulations !

**Comment by baiyutang** [comment]
> Hi, your request has been reviewed by the CloudWeGo community maintainer team and passed with majority approval.
> 
> You have been promoted as a member of [Kitex](https://github.com/cloudwego/kitex) Reviewer Team in CloudWeGo. Your certificate is [here](https://github.com/cloudwego/community/blob/main/Reviewer/baiyutang.pdf).
> 
> Please check [Responsibilities and privileges](https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md#responsibilities-and-privileges-2) for more details.
> 
> Congratulations !

Thank you~
