### ISSUE TITLE
REQUEST: New membership for <bodhisatan>

### ISSUE THREAD

**Issue by bodhisatan** [cloudwego/community#55]
### GitHub Username

bodhisatan

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md)
- [x] I have joined to the [Slack Channel](https://join.slack.com/t/cloudwego/shared_invite/zt-tmcbzewn-UjXMF3ZQsPhl7W3tEDZboA) and Feishu Group Chat (for Chinese)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more CloudWeGo repositories

#### fix: 
* https://github.com/cloudwego/kitex/pull/398
* https://github.com/hertz-contrib/jwt/pull/6
* https://github.com/kitex-contrib/registry-servicecomb/pull/2
* https://github.com/kitex-contrib/registry-etcd/pull/16
#### feat:
* https://github.com/hertz-contrib/jwt/pull/1
* https://github.com/hertz-contrib/swagger/pull/1
* https://github.com/kitex-contrib/registry-servicecomb/pull/1
* https://github.com/cloudwego/biz-demo/pull/24
* https://github.com/hertz-contrib/jwt/commit/b6635d79f1cc76fa7a2281dbc13c270aea01ead3
#### test:
* https://github.com/cloudwego/kitex/pull/392
#### doc:
* https://github.com/cloudwego/cloudwego.github.io/pull/162
* https://github.com/cloudwego/cloudwego.github.io/pull/191
* https://github.com/cloudwego/cloudwego.github.io/pull/180
#### chore:
* https://github.com/hertz-contrib/swagger/pull/2
* https://github.com/hertz-contrib/jwt/pull/2
* https://github.com/cloudwego/hertz/pull/29
* https://github.com/cloudwego/kitex/pull/268
#### code review:
* https://github.com/hertz-contrib/registry/pull/11
#### issues opened:
* https://github.com/cloudwego/kitex/issues/405
* https://github.com/cloudwego/hertz/issues/28

**Comment by li-jin-gou** [comment]
+1 ❤️

**Comment by L2ncE** [comment]
+1

**Comment by BaiZe1998** [comment]
+1

**Comment by rogerogers** [comment]
+1

**Comment by YangruiEmma** [comment]
Thanks for your contribution! +1

**Comment by baiyutang** [comment]
+1

**Comment by justlorain** [comment]
+ 1

**Comment by GuangmingLuo** [comment]
+1,  agree !

**Comment by welkeyever** [comment]
+1

**Comment by GuangmingLuo** [comment]
Hi, your request has been reviewed by the CloudWeGo community management team and passed with majority approval. Congratulations !

You have been invited to join [CloudWeGo](https://github.com/cloudwego) org, [kitex-contrib](https://github.com/kitex-contrib)  and [hertz-contrib](https://github.com/hertz-contrib) as a public member, as well as [Kitex](https://github.com/cloudwego/kitex) Committer Team in CloudWeGo. Your certificate is [here](https://github.com/cloudwego/community/blob/main/Committer/yaoxianjie.pdf).

Please check [Responsibilities and privileges](https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md#responsibilities-and-privileges-1) for more details.

Welcome to Join us !

**Comment by bodhisatan** [comment]
thank you all and I will keep learning and keep contributing to cwg!
