### ISSUE TITLE
REQUEST: New Reviewer for <justlorain>

### ISSUE THREAD

**Issue by justlorain** [cloudwego/community#56]
### GitHub Username

justlorain

### Requirements

- [x] Committer for at least 1 month
- [x] Primary reviewer for at least 5 PRs to the codebase
- [x] Reviewer for, or author of, at least 10 substantial PRs to the codebase, with the definition of substantial area to the maintainer's discretion (e.g. refactors/adds new functionality rather than one-line pulls)
- [x] Sponsored by a subproject maintainer
- [x] With no objections from other maintainers
- [x] May either self-nominate, be nominated by an maintainer in this subproject

### List of contributions to CloudWeGo

- [Committer for 2 months](https://github.com/cloudwego/community/issues/51)
- PRs reviewed 
  - [cloudwego/hertz-example (5)](https://github.com/cloudwego/hertz-examples/pulls?q=is%3Apr+is%3Amerged+reviewed-by%3Ajustlorain)
  - [hertz-contrib/registry (4)](https://github.com/hertz-contrib/registry/pulls?q=is%3Apr+is%3Amerged+reviewed-by%3Ajustlorain)
  - [cloudwego/cloudwego.github.io (13)](https://github.com/cloudwego/cloudwego.github.io/pulls?q=is%3Apr+is%3Amerged+reviewed-by%3Ajustlorain)
- PRs with new functionality
  - hertz
    - https://github.com/cloudwego/hertz/pull/375
    - https://github.com/cloudwego/hertz/pull/495
  - hertz-examples
    - https://github.com/cloudwego/hertz-examples/pull/51
    - https://github.com/cloudwego/hertz-examples/pull/58
    - https://github.com/cloudwego/hertz-examples/pull/47
  - hertz-contrib
    - https://github.com/hertz-contrib/jwt/pull/13
    - https://github.com/hertz-contrib/jwt/pull/15
    - https://github.com/hertz-contrib/requestid/pull/9
    - https://github.com/hertz-contrib/registry/pull/24
    - https://github.com/hertz-contrib/etag/pull/1
  - biz-demo
    - https://github.com/cloudwego/biz-demo/pull/13
    - https://github.com/cloudwego/biz-demo/pull/18
- Other
  - https://github.com/cloudwego/hertz/issues/567
  - https://github.com/cloudwego/hertz/issues/561
  - https://github.com/cloudwego/hertz/issues/399
  - https://github.com/cloudwego/hertz/issues/392
  - https://github.com/cloudwego/kitex-examples/issues/58
  - https://github.com/cloudwego/cloudwego.github.io/pull/503
  - https://github.com/cloudwego/kitex-examples/pull/56
  - https://github.com/hertz-contrib/registry/pull/28
  - https://github.com/cloudwego/hertz/pull/366
  - https://dev.to/justlorain/use-session-middleware-to-implement-distributed-session-solution-based-on-redis-5b65
  - https://dev.to/justlorain/an-interesting-process-of-solving-an-issue-5024

**Comment by welkeyever** [comment]
+1, looking forward to your next contribution to Hertz 😍

**Comment by GuangmingLuo** [comment]
+1

**Comment by cloudwegoIce** [comment]
+1 🎉

**Comment by FGYFFFF** [comment]
+1

**Comment by GuangmingLuo** [comment]
Hi, your request has been reviewed by the CloudWeGo community maintainer team and passed with majority approval.

You have been promoted as a member of [Hertz](https://github.com/cloudwego/hertz) Reviewer Team in CloudWeGo. Your certificate is [here](https://github.com/cloudwego/community/blob/main/Reviewer/justlorain.pdf).

Please check [Responsibilities and privileges](https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md#responsibilities-and-privileges-2) for more details.

Congratulations !

**Comment by justlorain** [comment]
Thanks for your help and I will continue to contribute to Cloudwego ☺️
