### ISSUE TITLE
REQUEST: New membership for <ii64>

### ISSUE THREAD

**Issue by ii64** [cloudwego/community#57]
### GitHub Username

ii64

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md)
- [x] I have joined to the [Slack Channel](https://join.slack.com/t/cloudwego/shared_invite/zt-tmcbzewn-UjXMF3ZQsPhl7W3tEDZboA) and Feishu Group Chat (for Chinese)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more CloudWeGo repositories

### List of contributions to CloudWeGo

- PRs reviewed / authored:
https://github.com/cloudwego/volo/pull/123
https://github.com/cloudwego/pilota/pull/83
https://github.com/cloudwego/pilota/pull/36

**Comment by PureWhiteWu** [comment]
+1
Thank you for all your contribution to CloudWeGo.

**Comment by GuangmingLuo** [comment]
+1  Great Job

**Comment by LYF1999** [comment]
+1

**Comment by Millione** [comment]
+1

**Comment by GuangmingLuo** [comment]
Hi, your request has been reviewed by the CloudWeGo-Volo community management team and passed with majority approval. Congratulations !

You have been invited to join [CloudWeGo](https://github.com/cloudwego) org as a public member, as well as [Volo](https://github.com/cloudwego/volo) Committer Team in CloudWeGo. Your certificate is [here](https://github.com/cloudwego/community/blob/main/Committer/Nugra.pdf).

Please check [Responsibilities and privileges](https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md#responsibilities-and-privileges-1) for more details.

Welcome to Join us !
