### ISSUE TITLE
[CSG 第四期] 精彩继续！ CloudWeGo 业务实践案例解读开始啦

### ISSUE THREAD

**Issue by Guandiyi** [cloudwego/community#58]
![image](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/c72a2f3b408a4f539275546ecebbfd92~tplv-k3u1fbpfcp-watermark.image?)

> ### 🌟CloudWeGo Study Group 
> 
> - CloudWeGo Study Group 是由 CloudWeGo 社区发起的学习小组。
> - CloudWeGo 是字节跳动开源的一套微服务中间件项目集合，是一个名副其实的三高项目：高性能、高扩展性、高可靠性。专注于解决微服务通信与治理的难题，满足不同业务在不同场景的诉求。
> - CloudWeGo 社区文化倡导技术交流和帮助开发者共同成长。
> - 因此我们成立了 CSG（CloudWeGo Study Group）——开展以 30 天为一期的源码解读和学习活动，帮助新成员融入社区圈子，和社区 Committer 互动交流，并学习上手 CloudWeGo 几大框架项目。
> 项目官网：https://www.cloudwego.io/

本期已经是 CSG 活动第四期啦！
本期主题是围绕如何基于 CloudWeGo 项目和生态搭建业务项目，社区 Committer 手把手教学，还有更多 Committer 参与社区的心路历程分享，尽请期待 ~
往期活动参考：https://github.com/cloudwego/community/issues/45

## 🎉活动信息
我们将采用 Study Group 形式，开展为期4周，每周一次社区分享的形式。为了更好的帮助大家理解  CloudWeGo 项目的使用场景和使用方式，社区基于CloudWeGo 项目搭建了[ biz-demo ](https://github.com/cloudwego/biz-demo)，为企业用户在生产中搭建业务提供有价值的参考。每个案例包含多个 CloudWeGo 子项目以及相关生态项目，例如项目中同时使用了 Kitex 和 Hertz，并演示一个单独的业务场景。

同时本期活动将会安排 4 期直播分享，分享围绕 CloudWeGo / biz-demo 的工程化实践：
- [Bookinfo——基于 CloudWeGo 重写 Istio 经典 demo](https://github.com/cloudwego/biz-demo/blob/main/bookinfo/README.md) ：用 Hertz 和 Kitex 重写经典的 Bookinfo 项目，展示工程设计、技术选型，再由浅入深展示用全链路泳道来实现灰度发布等场景。
- [Open Payment Platform——基于 CloudWeGo 实现 API Gateway](https://github.com/cloudwego/biz-demo/blob/main/open-payment-platform/README.md)：利用 Kitex 和 Hertz 进行支付开放平台的开发演示，使用 CloudWeGo 实现 API Gateway ，参考最佳实践，力求简洁、清晰得向大家展示效果。
- [EasyNote——CloudWeGo 生态入门](https://github.com/cloudwego/biz-demo/blob/main/easy_note/README.md)：如何快速入门 CloudWeGo 生态，biz-demo Easy Note 解读。
- [BookShop——从上手电商到上手CloudWeGo](https://github.com/cloudwego/biz-demo/blob/main/book-shop/README.md)：以从零搭建一个简易版电商系统为例，演示在Kitex/Hertz项目中如何集成中间件、设计架构、分层代码。

### 活动分享时间

本期活动周期：2.22 - 3.22 

| 活动参与时间       | 2.22-3.22 |         -- |
| :---------: | :--------------: | :-----------: | 
| 第一期分享     |  ![image](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/23cb0b4801264cc99b7271b83f0a9d8d~tplv-k3u1fbpfcp-zoom-1.image) | ⏰ 2. 22 19:30 直播间/回放：https://meetings.feishu.cn/s/1ipd8ih057fnm?src_type=2 / PPT:  [Bookinfo—基于 CloudWeGo 重写 Istio 经典 demo.pdf](https://github.com/cloudwego/community/blob/main/CSG/04/Bookinfo%E2%80%94%E5%9F%BA%E4%BA%8E%20CloudWeGo%20%E9%87%8D%E5%86%99%20Istio%20%E7%BB%8F%E5%85%B8%20demo.pdf) |  
| 第二/三期分享   |  ![image](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/c0364e61a4d14ec592e5c507346d5e3a~tplv-k3u1fbpfcp-watermark.image?) |   ⏰ 3. 8 19:30 直播间/回放：https://meetings.feishu.cn/s/1iraydxgioe81?src_type=2 / PPT:  [EasyNote——CloudWeGo 生态入门](https://github.com/cloudwego/community/blob/main/CSG/04/EasyNote%E2%80%94%E2%80%94CloudWeGo%20%E7%94%9F%E6%80%81%E5%85%A5%E9%97%A8.pdf) ;[OpenPaymentPlatform——基于CloudWeGo 实现 API Gateway](https://github.com/cloudwego/community/blob/main/CSG/04/OpenPaymentPlatform%E2%80%94%E2%80%94%E5%9F%BA%E4%BA%8ECloudWeGo%20%E5%AE%9E%E7%8E%B0%20API%20Gateway.pdf)|
| 第四期分享 | ![image](https://p6-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/6aea32f5ba5f4543bcff31ff1df65370~tplv-k3u1fbpfcp-watermark.image?) | ⏰ 3. 15 19:30 直播间/回放：https://meetings.feishu.cn/s/1is2wi7ytn8jl?src_type=2 / PPT: [BookShop——从上手电商到上手CloudWeGo](https://github.com/cloudwego/community/blob/main/CSG/04/BookShop-%E4%BB%8E%E4%B8%8A%E6%89%8B%E7%94%B5%E5%95%86%E5%88%B0%E4%B8%8A%E6%89%8BCloudWeGo.pdf) |

## 😊 参与会获得什么
1. 一个真正帮助你成长的社区组织。将会在 30 天 CSG 期间，每周安排一期分享，帮助学员理解和了解项目，同时吸收前辈的学习经验。
2. 直接对话社区 Maintainer 和项目大牛。学习过程中的问题社区会帮助学员共同解决，学员可以持续和社区共同成长！
3. 完成社区成长经验接力。贡献笔记、完成学习任务，即可获得 CSG 认证证书。同时有机会对 CloudWeGo 进行深入贡献，参与后续 CSG 活动分享以及社区例会和分享，还有机会获得字节跳动实习机会和内推名额。
提交笔记入口：https://zjsms.com/BXc1MpH/

![image](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/6fa02ab80c9f452b9396698ec598f4a4~tplv-k3u1fbpfcp-watermark.image?)

## 💻 参与方式
1. 对此次活动感兴趣的同学有以下两种参与方式：
- 关注本 Github CSG issue；
- 加入 CloudWeGo 飞书群，在群内进行技术交流和互动答疑。

![image](https://p1-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/71de1c61c2d84c088c7f57cff9a363b9~tplv-k3u1fbpfcp-watermark.image?)

2. 在相应 Issue 下或飞书群内交流学习内容，根据自己的学习需要，参与 CSG 直播分享。
3. 真实地输出自己的学习所得和反馈，以帮助下一届 CSG 成员。

**Comment by HeyJavaBean** [comment]
🎉
