### ISSUE TITLE
REQUEST: New Reviewer for <CoderPoet>

### ISSUE THREAD

**Issue by CoderPoet** [cloudwego/community#60]
### GitHub Username

e.g. CoderPoet

### Requirements

- [x] Committer for at least 1 month
- [x] Primary reviewer for at least 5 PRs to the codebase()
- [x] Reviewer for, or author of, at least 10 substantial PRs to the codebase, with the definition of substantial area to the maintainer's discretion (e.g. refactors/adds new functionality rather than one-line pulls)
- [x] Sponsored by a subproject maintainer
- [x] With no objections from other maintainers
- [x] May either self-nominate, be nominated by an maintainer in this subproject

### List of contributions to CloudWeGo

- [Committer for 12 months](https://github.com/cloudwego/community/issues/17)

- PRs with new functionality
   - [kitex-contrib/obs-opentelemetry](https://github.com/kitex-contrib/obs-opentelemetry/pulls?q=+is%3Apr+author%3A%40me+)
   - [hertz-contrib/obs-opentelemetry](https://github.com/hertz-contrib/obs-opentelemetry/pulls?q=+is%3Apr+author%3A%40me+)
   - [kitex-contrib/xds](https://github.com/kitex-contrib/xds/pulls?q=+is%3Apr+author%3A%40me+)
   - [cloudwego/biz-demo:bookinfo](https://github.com/cloudwego/biz-demo/pulls?q=is%3Apr+author%3A%40me)
   - [cloudwego/hertz-examples](https://github.com/cloudwego/hertz-examples/pulls?q=is%3Apr+author%3A%40me+)
   - [cloudwego/kitex-examples](https://github.com/cloudwego/kitex-examples/pulls?q=is%3Apr+author%3A%40me+)

- PRs reviewed
   - [kitex-contrib/obs-opentelemetry(7)](https://github.com/kitex-contrib/obs-opentelemetry/issues?q=assignee%3A%40me)
   - [hertz-contrib/obs-opentelemetry(7)](https://github.com/hertz-contrib/obs-opentelemetry/pulls?q=is%3Apr+)   
   - https://github.com/cloudwego/biz-demo/pull/29

- Issues responded to
   - https://github.com/cloudwego/kitex/issues/461
   - https://github.com/cloudwego/kitex/issues/849
   - https://github.com/hertz-contrib/obs-opentelemetry/issues/17
   - https://github.com/hertz-contrib/obs-opentelemetry/issues/16
   - https://github.com/kitex-contrib/obs-opentelemetry/issues/7

- Other
   - [kitex-proxyless-practice-traffic-lane-implementation-with-istio-and-opentelemetry](https://www.cncf.io/blog/2023/01/11/kitex-proxyless-practice-traffic-lane-implementation-with-istio-and-opentelemetry/)
   - https://github.com/cloudwego/community/issues/58

**Comment by GuangmingLuo** [comment]
+ 1

**Comment by jayantxie** [comment]
+1

**Comment by cloudwegoIce** [comment]
+1  Congratulations ! 🎉🎉🎉

**Comment by ppzqh** [comment]
+1

**Comment by FGYFFFF** [comment]
+1 Congratulations ! 🎉🎉🎉

**Comment by YangruiEmma** [comment]
Strongly support! Thanks for your big contribution!

**Comment by welkeyever** [comment]
+1, welcome~

**Comment by GuangmingLuo** [comment]
Hi, your request has been reviewed by the CloudWeGo community maintainer team and passed with majority approval.

You have been promoted as a member of [Kitex](https://github.com/cloudwego/kitex) Reviewer Team in CloudWeGo. Your certificate is [here](https://github.com/cloudwego/community/blob/main/Reviewer/CoderPoet.pdf).

Please check [Responsibilities and privileges](https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md#responsibilities-and-privileges-2) for more details.

Congratulations !
