### ISSUE TITLE
REQUEST: New Reviewer for <rogerogers>

### ISSUE THREAD

**Issue by rogerogers** [cloudwego/community#61]
### GitHub Username

@rogerogers

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md)
- [x] I have joined to the [Slack Channel](https://join.slack.com/t/cloudwego/shared_invite/zt-tmcbzewn-UjXMF3ZQsPhl7W3tEDZboA) and Feishu Group Chat (for Chinese)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more CloudWeGo repositories

### List of contributions to CloudWeGo

- [Committer for 7 months](https://github.com/cloudwego/community/issues/42)
- PRs reviewed / authored
  - docs
    - https://github.com/cloudwego/cloudwego.github.io/pull/390
    - https://github.com/cloudwego/cloudwego.github.io/pull/395
    - https://github.com/cloudwego/cloudwego.github.io/pull/413
    - https://github.com/cloudwego/cloudwego.github.io/pull/424
    - https://github.com/cloudwego/cloudwego.github.io/pull/427
    - https://github.com/cloudwego/cloudwego.github.io/pull/432
    - https://github.com/cloudwego/cloudwego.github.io/pull/433
    - https://github.com/cloudwego/cloudwego.github.io/pull/439
    - https://github.com/cloudwego/cloudwego.github.io/pull/449
    - https://github.com/cloudwego/cloudwego.github.io/pull/454
    - https://github.com/cloudwego/cloudwego.github.io/pull/460
    - https://github.com/cloudwego/cloudwego.github.io/pull/527
    - https://github.com/cloudwego/cloudwego.github.io/pull/528
    - https://github.com/cloudwego/cloudwego.github.io/pull/531
    - https://github.com/cloudwego/cloudwego.github.io/pull/546
    - https://github.com/cloudwego/cloudwego.github.io/pull/589
    - https://github.com/cloudwego/cloudwego.github.io/pull/601
    - https://github.com/cloudwego/cloudwego.github.io/pull/603
    - https://github.com/cloudwego/cloudwego.github.io/pull/593
  - hertz
    - https://github.com/hertz-contrib/logger/pull/3
    - https://github.com/hertz-contrib/logger/pull/25
    - https://github.com/hertz-contrib/logger/pull/19
    - https://github.com/hertz-contrib/obs-opentelemetry/pull/15
  - kitex
    - https://github.com/cloudwego/kitex-examples/pull/48
    - https://github.com/kitex-contrib/obs-opentelemetry/pull/14
    - https://github.com/kitex-contrib/monitor-prometheus/pull/11
    - https://github.com/kitex-contrib/obs-opentelemetry/pull/16
  - cwgo
    - https://github.com/cloudwego/cwgo/pull/39
    - https://github.com/cloudwego/cwgo/pull/41

- Issues responded to
  - https://github.com/cloudwego/cwgo/issues/40
  - https://github.com/cloudwego/hertz/issues/620
  - https://github.com/cloudwego/cwgo/issues/38
  - https://github.com/cloudwego/kitex/issues/895
  - https://github.com/kitex-contrib/obs-opentelemetry/issues/18

**Comment by GuangmingLuo** [comment]
+1

**Comment by Duslia** [comment]
+1 Welcome

**Comment by welkeyever** [comment]
+1, welcome~

**Comment by li-jin-gou** [comment]
+1  Thank you for your contribution.

**Comment by FGYFFFF** [comment]
+1 Thank you for your contribution~~~~

**Comment by cloudwegoIce** [comment]
+1 Thanks for your contribution & Welcome to be a Reviewer 🎉🎉

**Comment by GuangmingLuo** [comment]
Hi, your request has been reviewed by the CloudWeGo community maintainer team and passed with majority approval.

You have been promoted as a member of [Website & Docs](https://github.com/orgs/cloudwego/teams/website-docs) Reviewer Team in CloudWeGo. Your certificate is [here](https://github.com/cloudwego/community/blob/main/Reviewer/rogerogers.pdf).

Please check [Responsibilities and privileges](https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md#responsibilities-and-privileges-2) for more details.

Congratulations !
