### ISSUE TITLE
REQUEST: New Reviewer for Skyenought

### ISSUE THREAD

**Issue by Skyenought** [cloudwego/community#65]
### GitHub Username

@Skyenought 

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md)
- [x] I have joined to the [Slack Channel](https://join.slack.com/t/cloudwego/shared_invite/zt-tmcbzewn-UjXMF3ZQsPhl7W3tEDZboA) and Feishu Group Chat (for Chinese)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more CloudWeGo repositories

### List of contributions to CloudWeGo

- [Committer for 9 mouths](https://github.com/cloudwego/community/issues/35)
- PRs reviewed / authored
  - docs
    - reviewed
      - https://github.com/cloudwego/cloudwego.github.io/pull/789
    - authored 
      - https://github.com/cloudwego/cloudwego.github.io/pull/787 
      - https://github.com/cloudwego/cloudwego.github.io/pull/791
      - https://github.com/cloudwego/cloudwego.github.io/pull/328
      - https://github.com/cloudwego/cloudwego.github.io/pull/337
      - https://github.com/cloudwego/cloudwego.github.io/pull/372
      - https://github.com/cloudwego/cloudwego.github.io/pull/405
      - https://github.com/cloudwego/cloudwego.github.io/pull/407
      - https://github.com/cloudwego/cloudwego.github.io/pull/419
      - https://github.com/cloudwego/cloudwego.github.io/pull/421
      - https://github.com/cloudwego/cloudwego.github.io/pull/440
      - https://github.com/cloudwego/cloudwego.github.io/pull/524
      - https://github.com/cloudwego/cloudwego.github.io/pull/552
      - https://github.com/cloudwego/cloudwego.github.io/pull/558
      - https://github.com/cloudwego/cloudwego.github.io/pull/577
      - https://github.com/cloudwego/cloudwego.github.io/pull/602
      - https://github.com/cloudwego/cloudwego.github.io/pull/641
  - cwgo
    - authored 
        - https://github.com/cloudwego/cwgo/pull/45
        - https://github.com/cloudwego/cwgo/pull/48
        - https://github.com/cloudwego/cwgo/pull/49
        - https://github.com/cloudwego/cwgo/pull/50
        - https://github.com/cloudwego/cwgo/pull/51
  - hertz-contrib
    - reviewed 
      - https://github.com/hertz-contrib/gzip/pull/9 
      - https://github.com/hertz-contrib/registry/pull/34
      - https://github.com/hertz-contrib/sse/pull/2
      - https://github.com/hertz-contrib/sessions/pull/9
      - https://github.com/hertz-contrib/reverseproxy/pull/5
      - https://github.com/hertz-contrib/websocket/pull/1
      - https://github.com/hertz-contrib/keyauth/pull/1
      - https://github.com/hertz-contrib/obs-opentelemetry/pull/6
      - https://github.com/hertz-contrib/secure/pull/1
      - https://github.com/hertz-contrib/hertzsentry/pull/1
      - https://github.com/hertz-contrib/pprof/pull/1
      - https://github.com/hertz-contrib/logger/pull/2
    - authored
      - https://github.com/hertz-contrib/logger/pull/33
      - https://github.com/hertz-contrib/registry/pull/83
  - hertz
    - authored
      - https://github.com/cloudwego/hertz/pull/819  
    - reviewed
      - https://github.com/cloudwego/hertz/pull/456 
     
  - Issues responded to
    - https://github.com/cloudwego/hertz/issues/613
    - https://github.com/cloudwego/hertz/issues/957
    - https://github.com/hertz-contrib/logger/issues/32

**Comment by GuangmingLuo** [comment]
Thanks for your contribution. As we dicussed, contribution needs to be more focused to be a SIG reviewer. We will hold this request for a while.

**Comment by li-jin-gou** [comment]
I found some contributions that were duplicates and commiter applications.

**Comment by li-jin-gou** [comment]
Some code reviews Please indicate that they are code reviews.

**Comment by welkeyever** [comment]
If you are applying for the role of framework reviewer, you may focus on adding the information of the review PR you have participated in. This will be an important reference.🤗

**Comment by li-jin-gou** [comment]
Please distinguish between code review and feature

**Comment by li-jin-gou** [comment]
@Skyenought  I don't have permission to reopen this application, so I'd like to reopen it and add the most recent developments, including the issues and pr you've been involved in.

**Comment by GuangmingLuo** [comment]
Support for Web&Doc reviewer

**Comment by li-jin-gou** [comment]
Support for Web&Doc reviewer +1❤️

**Comment by Duslia** [comment]
Welcode +1

**Comment by FGYFFFF** [comment]
Support for Web&Doc reviewer~   welcome~✌️✌️✌️

**Comment by welkeyever** [comment]
Good job! Welcome~

**Comment by pkumza** [comment]
Welcome +1

**Comment by GuangmingLuo** [comment]
Hi, your request has been reviewed by the CloudWeGo community maintainer team and passed with majority approval.

You have been promoted as a member of [Website & Docs](https://github.com/orgs/cloudwego/teams/website-docs) Reviewer Team in CloudWeGo. Your certificate is [here](https://github.com/cloudwego/community/blob/main/Reviewer/Skyenought.pdf).

Please check [Responsibilities and privileges](https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md#responsibilities-and-privileges-2) for more details.

Congratulations !
