### ISSUE TITLE
[CSG 第五期] 源码解读 & 项目实战！ Hertz 中间件实战解读开始啦

### ISSUE THREAD

**Issue by Guandiyi** [cloudwego/community#66]
![image](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/99893f122aa345d68f927f2acbd56372~tplv-k3u1fbpfcp-watermark.image?)

> ### 🌟CloudWeGo Study Group 
> 
> - CloudWeGo Study Group 是由 CloudWeGo 社区发起的学习小组。
> - CloudWeGo 是字节跳动开源的一套微服务中间件项目集合，是一个名副其实的三高项目：高性能、高扩展性、高可靠性。专注于解决微服务通信与治理的难题，满足不同业务在不同场景的诉求。
> - CloudWeGo 社区文化倡导技术交流和帮助开发者共同成长。
> - 因此我们成立了 CSG（CloudWeGo Study Group）——开展以 30 天为一期的源码解读和学习活动，帮助新成员融入社区圈子，和社区 Committer 互动交流，并学习上手 CloudWeGo 几大框架项目。
> 项目官网：https://www.cloudwego.io/

本期已经是 CSG 活动第五期啦！
本期主题是围绕 Hertz 中间件实战，分享“源码解读”和“项目实战”，社区 Committer 手把手教学，还有更多 Committer 参与社区的心路历程分享，尽请期待 ~
往期活动参考：https://github.com/cloudwego/community/issues/58

## 🎉活动信息
我们将采用 Study Group 形式，开展为期4周，每周一次社区分享的形式。为了更好的帮助大家理解 Hertz 适配的中间件及其实现，为中间件适配提供有价值的参考，每次分享包含 Hertz 的开发及使用分享，包含 Hertz 中间件梳理，Hertz Server/Client 中间件源码分析与实现。

同时本期活动将会安排 3 期直播分享，分享围绕 Hertz 中间件源码解读和项目实战：
1. **Hertz 中间件简介、分类与实现原理**：针对 Hertz 中间件进行介绍，包括 Hertz 中间件的分类、梳理、简介与使用场景，分享 Server 端与 Client 端中间件链的实现原理。
2. **如何使用 hertz 的中间件拓展能力快速开发业务应用**：分享 Herz Server 的 Session 中间件实现、CSRF中间件实战等，并分享通过一个 Hertz client 来访问 Server，提出 hertz client 超时中间件的使用能力。
3. **如何快速开发适合自己业务的 Hertz 中间件**：结合 Session/CSRF 的使用分享，来介绍 Session/CSRF 的设计思路和方法；分享 Client 中间件拓展，介绍服务发现/超时的设计。

### 活动分享时间

本期活动周期：5.31 - 6.30 

| 活动参与时间       | 5.31 - 6.30 |         -- |
| :---------: | :--------------: | :-----------: | 
| 第一期分享     |  ![image](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/b4a3fd1d95484fb68ec239e509a812ce~tplv-k3u1fbpfcp-watermark.image?) |  ⏰ 6. 10 19:30 直播间/回放：https://meetings.feishu.cn/s/1iz6pbraqy51e?src_type=2 / PPT:  [探索 Hertz 中间件：用法、生态及实现原理.pdf](https://github.com/cloudwego/community/blob/main/CSG/05/%E6%8E%A2%E7%B4%A2%20Hertz%20%E4%B8%AD%E9%97%B4%E4%BB%B6%EF%BC%9A%E7%94%A8%E6%B3%95%E3%80%81%E7%94%9F%E6%80%81%E5%8F%8A%E5%AE%9E%E7%8E%B0%E5%8E%9F%E7%90%86.pdf) |  
| 第二期分享   | ![image](https://p6-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/f08b96707ad34a0c964e93c102d8d185~tplv-k3u1fbpfcp-watermark.image?)|   ⏰ 6. 10 19:30 直播间/回放：https://meetings.feishu.cn/s/1j0tmh547vx1g?src_type=2 / PPT:  [Hertz-Session：解读 Hertz Middleware.pdf](https://github.com/cloudwego/community/blob/main/CSG/05/Hertz-Session%EF%BC%9A%E8%A7%A3%E8%AF%BB%20Hertz%20Middleware.pdf)|
| 第三期分享 | ![image](https://p6-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/12a0f9c2b65447b686ffb6beed642781~tplv-k3u1fbpfcp-watermark.image?) | ⏰ 6. 17 19:30 直播间/回放：https://meetings.feishu.cn/s/1j1gs6udypv5w?src_type=2 / PPT: [快速掌握适合自己业务的 Hertz 中间件.pdf](https://github.com/cloudwego/community/blob/main/CSG/05/%E5%BF%AB%E9%80%9F%E6%8E%8C%E6%8F%A1%E9%80%82%E5%90%88%E8%87%AA%E5%B7%B1%E4%B8%9A%E5%8A%A1%E7%9A%84%20Hertz%20%E4%B8%AD%E9%97%B4%E4%BB%B6.pdf)|

## 😊 参与会获得什么
1. 一个真正帮助你成长的社区组织。将会在 30 天 CSG 期间，每周安排一期分享，帮助学员理解和了解项目，同时吸收前辈的学习经验。
2. 直接对话社区 Maintainer 和项目大牛。学习过程中的问题社区会帮助学员共同解决，学员可以持续和社区共同成长！
3. 完成社区成长经验接力。贡献笔记、完成学习任务，即可获得 CSG 认证证书。同时有机会对 CloudWeGo 进行深入贡献，参与后续 CSG 活动分享以及社区例会和分享，还有机会获得字节跳动实习机会和内推名额。
提交笔记入口：https://zjsms.com/BXc1MpH/

![image](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/6fa02ab80c9f452b9396698ec598f4a4~tplv-k3u1fbpfcp-watermark.image?)

## 💻 参与方式
1. 对此次活动感兴趣的同学有以下两种参与方式：
- 关注本 Github CSG issue；
- 加入 CloudWeGo 飞书群，在群内进行技术交流和互动答疑。

![image](https://p1-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/71de1c61c2d84c088c7f57cff9a363b9~tplv-k3u1fbpfcp-watermark.image?)

2. 在相应 Issue 下或飞书群内交流学习内容，根据自己的学习需要，参与 CSG 直播分享。
3. 真实地输出自己的学习所得和反馈，以帮助下一届 CSG 成员。

**Comment by GuangmingLuo** [comment]
Welcome to join us !

**Comment by Milkve** [comment]
I am coming! Could I post my notes on juejin, and how could you know the notes are uploaded by me?

**Comment by GuangmingLuo** [comment]
> I am coming! Could I post my notes on juejin, and how could you know the notes are uploaded by me?

@Milkve Please post your blog link here.

**Comment by Skyenought** [comment]
为什么笔记提交入口无访问权限呢?

**Comment by Guandiyi** [comment]
> 为什么笔记提交入口无访问权限呢?

@Skyenought 抱歉，目前已经调整了提交入口权限，辛苦再次提交了❤️
