### ISSUE TITLE
REQUEST: New membership for <a631807682>

### ISSUE THREAD

**Issue by a631807682** [cloudwego/community#68]
### GitHub Username

a631807682

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md)
- [x] I have joined to the [Slack Channel](https://join.slack.com/t/cloudwego/shared_invite/zt-tmcbzewn-UjXMF3ZQsPhl7W3tEDZboA) and Feishu Group Chat (for Chinese)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more CloudWeGo repositories

### List of contributions to CloudWeGo

- Doc Contribution
	- https://github.com/cloudwego/cloudwego.github.io/pull/569
	- https://github.com/cloudwego/cloudwego.github.io/pull/588
	- https://github.com/cloudwego/cloudwego.github.io/pull/681
	- https://github.com/cloudwego/cloudwego.github.io/pull/619
- Code Contribution
	- https://github.com/hertz-contrib/registry/pull/15
	- https://github.com/hertz-contrib/registry/pull/37
	- https://github.com/cloudwego/hertz/pull/669
	- https://github.com/cloudwego/hertz/pull/672
	- https://github.com/cloudwego/hertz/pull/686
	- https://github.com/cloudwego/hertz/pull/687
	- https://github.com/cloudwego/hertz/pull/804
	- https://github.com/cloudwego/hertz/pull/817
- Issues about CloudWeGo
	- https://github.com/cloudwego/cloudwego.github.io/issues/302
	- https://github.com/cloudwego/cloudwego.github.io/issues/626
	- https://github.com/cloudwego/hertz/issues/222
	- https://github.com/cloudwego/kitex/issues/597

**Comment by welkeyever** [comment]
+1, LGTM

**Comment by GuangmingLuo** [comment]
+1, LGTM

**Comment by li-jin-gou** [comment]
+1, LGTM

**Comment by baiyutang** [comment]
+1, LGTM

**Comment by liu-song** [comment]
+1, LGTM

**Comment by Duslia** [comment]
+1, Welcome

**Comment by FGYFFFF** [comment]
+1, Welcome

**Comment by GuangmingLuo** [comment]
Hi, your request has been reviewed by the CloudWeGo community management team and passed with majority approval. Congratulations !

You have been invited to join [CloudWeGo](https://github.com/cloudwego) org and [hertz-contrib](https://github.com/hertz-contrib) as a public member, as well as [Hertz](https://github.com/cloudwego/hertz) Committer Team in CloudWeGo. Your certificate is [here](https://github.com/cloudwego/community/blob/main/Committer/a631807682.pdf).

Please check [Responsibilities and privileges](https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md#responsibilities-and-privileges-1) for more details.

Welcome to Join us !
