### ISSUE TITLE
REQUEST: New Approver for <rogerogers>

### ISSUE THREAD

**Issue by rogerogers** [cloudwego/community#71]
### GitHub Username

@rogerogers

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md)
- [x] I have joined to the [Slack Channel](https://join.slack.com/t/cloudwego/shared_invite/zt-tmcbzewn-UjXMF3ZQsPhl7W3tEDZboA) and Feishu Group Chat (for Chinese)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more CloudWeGo repositories

### List of contributions to CloudWeGo

- [Reviewer for 3 months](https://github.com/cloudwego/community/issues/42)
- PRs authored

  - https://github.com/cloudwego/cwgo/pull/56
  - https://github.com/cloudwego/hertz-examples/pull/91
  - https://github.com/cloudwego/cloudwego.github.io/pull/615
  - https://github.com/hertz-contrib/cors/pull/4
  - https://github.com/cloudwego/cloudwego.github.io/pull/627
  - https://github.com/cloudwego/cloudwego.github.io/pull/628
  - https://github.com/hertz-contrib/obs-opentelemetry/pull/20
  - https://github.com/kitex-contrib/obs-opentelemetry/pull/20
  - https://github.com/hertz-contrib/http2/pull/20
  - https://github.com/cloudwego/cloudwego.github.io/pull/655
  - https://github.com/hertz-contrib/obs-opentelemetry/pull/21
  - https://github.com/kitex-contrib/obs-opentelemetry/pull/22
  - https://github.com/cloudwego/cloudwego.github.io/pull/669
  - https://github.com/cloudwego/cloudwego.github.io/pull/671
  - https://github.com/cloudwego/cloudwego.github.io/pull/709
  - https://github.com/cloudwego/cloudwego.github.io/pull/741
  - https://github.com/cloudwego/cloudwego.github.io/pull/742
  - https://github.com/cloudwego/cloudwego.github.io/pull/743
  - https://github.com/cloudwego/cloudwego.github.io/pull/745
  - https://github.com/cloudwego/cloudwego.github.io/pull/751

- PRs reviewed:

  - https://github.com/cloudwego/cloudwego.github.io/pull/662
  - https://github.com/hertz-contrib/logger/pull/27
  - https://github.com/cloudwego/cloudwego.github.io/pull/623
  - https://github.com/hertz-contrib/logger/pull/33
  - https://github.com/cloudwego/cloudwego.github.io/pull/661
  - https://github.com/cloudwego/cloudwego.github.io/pull/643
  - https://github.com/cloudwego/cloudwego.github.io/pull/595
  - https://github.com/cloudwego/cloudwego.github.io/pull/612
  - https://github.com/cloudwego/cloudwego.github.io/pull/660
  - https://github.com/cloudwego/cwgo/pull/66

- Issues responded to
  - https://github.com/cloudwego/cloudwego.github.io/issues/668
  - https://github.com/cloudwego/cloudwego.github.io/issues/631
  - https://github.com/cloudwego/cloudwego.github.io/issues/608
  - https://github.com/cloudwego/cloudwego.github.io/issues/750
  - https://github.com/cloudwego/hertz/issues/861
  - https://github.com/cloudwego/hertz/issues/723
  - https://github.com/cloudwego/hertz/issues/786
  - https://github.com/cloudwego/hertz/issues/773
  - https://github.com/hertz-contrib/obs-opentelemetry/issues/18
  - https://github.com/kitex-contrib/obs-opentelemetry/issues/21
  - https://github.com/kitex-contrib/obs-opentelemetry/issues/19
  - https://github.com/hertz-contrib/logger/issues/26

**Comment by GuangmingLuo** [comment]
+1 LGTM

**Comment by HeyJavaBean** [comment]
coool~

**Comment by li-jin-gou** [comment]
+1

**Comment by YangruiEmma** [comment]
Thanks for your contribution! +1

**Comment by welkeyever** [comment]
Good job! Thanks a lot, and welcome~

**Comment by GuangmingLuo** [comment]
Hi, your request has been reviewed by the CloudWeGo community maintainer team and passed with majority approval.

You have been promoted as a member of [Website & Docs](https://github.com/orgs/cloudwego/teams/website-docs) Approver Team in CloudWeGo. Your certificate is [here](https://github.com/cloudwego/community/blob/main/Approver/rogerogers.pdf).

Please check [Responsibilities and privileges](https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md#responsibilities-and-privileges-3) for more details.

Congratulations !
