### ISSUE TITLE
REQUEST: New membership for <whalecold>

### ISSUE THREAD

**Issue by whalecold** [cloudwego/community#73]
### GitHub Username
whalecold

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md)
- [x] I have joined to the [Slack Channel](https://join.slack.com/t/cloudwego/shared_invite/zt-tmcbzewn-UjXMF3ZQsPhl7W3tEDZboA) and Feishu Group Chat (for Chinese)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more CloudWeGo repositories

### List of contributions to CloudWeGo

- kitex

  - Issue
    - https://github.com/cloudwego/kitex/issues/1042
  - Pull Requests
    - https://github.com/cloudwego/kitex/pull/1083
    - https://github.com/cloudwego/kitex/pull/1058
    - https://github.com/cloudwego/kitex/pull/1048
    - https://github.com/cloudwego/kitex/pull/1038
    - https://github.com/cloudwego/kitex/pull/1035
- hertz
  - Doc
    - https://github.com/cloudwego/cloudwego.github.io/pull/576 

- config-nacos
  - Issue
    - https://github.com/kitex-contrib/config-nacos/issues/5
  - Feature
    - https://github.com/kitex-contrib/config-nacos/pull/4
    - https://github.com/kitex-contrib/config-nacos/pull/3
    - https://github.com/kitex-contrib/config-nacos/pull/2
    - https://github.com/kitex-contrib/config-nacos/pull/1
- hertz-contrib
  - Pull Requests
    - https://github.com/hertz-contrib/logger/pull/22

**Comment by GuangmingLuo** [comment]
+1, support

**Comment by rogerogers** [comment]
+1, 🎉

**Comment by felix021** [comment]
+1, support

**Comment by ppzqh** [comment]
+1, support

**Comment by baiyutang** [comment]
+1, 🎉

**Comment by CoderPoet** [comment]
+1, Li Master YYDS

**Comment by YangruiEmma** [comment]
Thanks for your contributes! Support!
