### ISSUE TITLE
REQUEST: New membership for <chaoranz758>

### ISSUE THREAD

**Issue by chaoranz758** [cloudwego/community#74]
### GitHub Username

chaoranz758

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md)
- [x] I have joined to the [Slack Channel](https://join.slack.com/t/cloudwego/shared_invite/zt-tmcbzewn-UjXMF3ZQsPhl7W3tEDZboA) and Feishu Group Chat (for Chinese)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more CloudWeGo repositories

### List of contributions to CloudWeGo

- PRs reviewed / authored
  - docs
    - https://github.com/cloudwego/cloudwego.github.io/pull/619
    - https://github.com/cloudwego/cloudwego.github.io/pull/688
    - https://github.com/cloudwego/cloudwego.github.io/pull/722
    - https://github.com/cloudwego/cloudwego.github.io/pull/723
    - https://github.com/cloudwego/cloudwego.github.io/pull/725
    - https://github.com/cloudwego/cloudwego.github.io/pull/732
    - https://github.com/cloudwego/cloudwego.github.io/pull/733
    - https://github.com/cloudwego/cloudwego.github.io/pull/737
    - https://github.com/cloudwego/cloudwego.github.io/pull/744
    - https://github.com/cloudwego/cloudwego.github.io/pull/746
    - https://github.com/cloudwego/cloudwego.github.io/pull/747
    - https://github.com/cloudwego/cloudwego.github.io/pull/748
    - https://github.com/cloudwego/cloudwego.github.io/pull/752
    - https://github.com/cloudwego/cloudwego.github.io/pull/753
    - https://github.com/cloudwego/cloudwego.github.io/pull/754
    - https://github.com/cloudwego/cloudwego.github.io/pull/758
    - https://github.com/cloudwego/cloudwego.github.io/pull/760
    - https://github.com/cloudwego/cloudwego.github.io/pull/761
    - https://github.com/cloudwego/cloudwego.github.io/pull/762
    - https://github.com/cloudwego/cloudwego.github.io/pull/768
    - https://github.com/cloudwego/cloudwego.github.io/pull/772
    - https://github.com/cloudwego/cloudwego.github.io/pull/773
    - https://github.com/cloudwego/cloudwego.github.io/pull/774
    - https://github.com/cloudwego/cloudwego.github.io/pull/775
    - https://github.com/cloudwego/cloudwego.github.io/pull/777
    - https://github.com/cloudwego/cloudwego.github.io/pull/780
  - hertz
    - https://github.com/cloudwego/hertz/pull/863
    - https://github.com/cloudwego/hertz/pull/941
    - https://github.com/cloudwego/hertz/pull/942
    - https://github.com/cloudwego/hertz/pull/950
    - https://github.com/cloudwego/hertz-examples/pull/111
    - https://github.com/cloudwego/hertz-examples/pull/114
  - kitex
    - https://github.com/kitex-contrib/registry-etcd/pull/29 

- Issues responded to
  - https://github.com/cloudwego/hertz/issues/908
  - https://github.com/cloudwego/hertz/issues/949
  - https://github.com/cloudwego/kitex/issues/1105

**Comment by GuangmingLuo** [comment]
+1, support

**Comment by li-jin-gou** [comment]
+1, support

**Comment by welkeyever** [comment]
+1, welcome~

**Comment by rogerogers** [comment]
+1, welcome

**Comment by YangruiEmma** [comment]
+1, support

**Comment by Duslia** [comment]
+1 Welcome

**Comment by FGYFFFF** [comment]
+1, welcome~~~👍

**Comment by GuangmingLuo** [comment]
Hi, your request has been reviewed by the CloudWeGo community management team and passed with majority approval. Congratulations !

You have been invited to join [CloudWeGo](https://github.com/cloudwego) org as a public member, as well as Website & Docs Committer Team in CloudWeGo. Your certificate is [here](https://github.com/cloudwego/community/blob/main/Committer/luruichao.pdf)

Please check [Responsibilities and privileges](https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md#responsibilities-and-privileges-1) for more details.

Welcome to Join us !
