### ISSUE TITLE
REQUEST: New membership for <DMwangnima>

### ISSUE THREAD

**Issue by DMwangnima** [cloudwego/community#76]
### GitHub Username

@DMwangnima

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md)
- [x] I have joined to the [Slack Channel](https://join.slack.com/t/cloudwego/shared_invite/zt-tmcbzewn-UjXMF3ZQsPhl7W3tEDZboA) and Feishu Group Chat (for Chinese)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more CloudWeGo repositories

### List of contributions to CloudWeGo

- kitex
    - Feature
        - https://github.com/cloudwego/kitex/pull/1069
- codec-dubbo
    - Feature
        - https://github.com/kitex-contrib/codec-dubbo/pull/25
        - https://github.com/kitex-contrib/codec-dubbo/pull/26
        - https://github.com/kitex-contrib/codec-dubbo/pull/27
        - https://github.com/kitex-contrib/codec-dubbo/pull/29
        - https://github.com/kitex-contrib/codec-dubbo/pull/30
        - https://github.com/kitex-contrib/codec-dubbo/pull/31
        - https://github.com/kitex-contrib/codec-dubbo/pull/32
        - https://github.com/kitex-contrib/codec-dubbo/pull/34
        - https://github.com/kitex-contrib/codec-dubbo/pull/40
        - https://github.com/kitex-contrib/codec-dubbo/pull/41
        - https://github.com/kitex-contrib/codec-dubbo/pull/43
        - https://github.com/kitex-contrib/codec-dubbo/pull/44
        - https://github.com/kitex-contrib/codec-dubbo/pull/45
        - https://github.com/kitex-contrib/codec-dubbo/pull/47
        - https://github.com/kitex-contrib/codec-dubbo/pull/49

**Comment by felix021** [comment]
+1, support.

@DMwangnima is the main contributor to the DubboCodec project, where he has spearheaded the implementation of the Dubbo protocol's Codec. He has not only developed the core Codec but also provided a wealth of illustrative examples, including kitex-kitex/kitex-dubbo/dubbo-kitex, conducted performance tests, and prepared user documentation. His work stands out for its quality and dedication, playing a pivotal role in the project's success.

**Comment by GuangmingLuo** [comment]
+ support

**Comment by baiyutang** [comment]
+1

**Comment by liu-song** [comment]
+1 support

**Comment by YangruiEmma** [comment]
Strongly support! Thanks for your hard work and big contribution!

**Comment by GuangmingLuo** [comment]
Hi, your request has been reviewed by the CloudWeGo Kitex management team and passed with majority approval. Congratulations !

You have been invited to join [CloudWeGo](https://github.com/cloudwego) org and [kitex-contrib](https://github.com/kitex-contrib) as a public member, as well as [Kitex](https://github.com/cloudwego/kitex) Committer Team in CloudWeGo. Your certificate is [here](https://github.com/cloudwego/community/blob/main/Committer/DMwangnima.pdf).

Please check [Responsibilities and privileges](https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md#responsibilities-and-privileges-1) for more details.

Welcome to Join us !
