### ISSUE TITLE
REQUEST: New membership for <ViolaPioggia>

### ISSUE THREAD

**Issue by ViolaPioggia** [cloudwego/community#77]
### GitHub Username

ViolaPioggia

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md)
- [x] I have joined to the [Slack Channel](https://join.slack.com/t/cloudwego/shared_invite/zt-tmcbzewn-UjXMF3ZQsPhl7W3tEDZboA) and Feishu Group Chat (for Chinese)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more CloudWeGo repositories

### List of contributions to CloudWeGo

- PRs reviewed / authored
hertz :
https://github.com/cloudwego/hertz-examples/pull/95
https://github.com/cloudwego/cloudwego.github.io/pull/639
https://github.com/cloudwego/hertz/pull/869
https://github.com/cloudwego/cloudwego.github.io/pull/789
https://github.com/cloudwego/cloudwego.github.io/pull/811
https://github.com/cloudwego/hertz-examples/pull/119
https://github.com/cloudwego/cloudwego.github.io/pull/811
https://github.com/hertz-contrib/sse/pull/4
https://github.com/hertz-contrib/registry/pull/92
https://github.com/hertz-contrib/sse/pull/5
https://github.com/cloudwego/cloudwego.github.io/pull/854
https://github.com/hertz-contrib/sse/pull/11
kitex :
https://github.com/cloudwego/kitex/issues/1140
https://github.com/kitex-contrib/config-etcd/pull/1
https://github.com/kitex-contrib/config-etcd/pull/2
https://github.com/kitex-contrib/config-etcd/pull/3
https://github.com/kitex-contrib/config-etcd/pull/5
https://github.com/cloudwego/kitex-examples/pull/84
https://github.com/kitex-contrib/obs-opentelemetry/pull/33
https://github.com/cloudwego/cloudwego.github.io/pull/867
https://github.com/kitex-contrib/config-etcd/pull/5
CR :
https://github.com/hertz-contrib/sse/pull/12
https://github.com/kitex-contrib/config-apollo/pull/2
https://github.com/kitex-contrib/config-zookeeper/pull/1

**Comment by li-jin-gou** [comment]
Thank you for your contribution.

**Comment by li-jin-gou** [comment]
A code review can also be added, but it should be specified as a code review.

**Comment by li-jin-gou** [comment]
+1 Thank you for contributing to kitex and hertz, these features have been well received by real users. I hope you can contribute more features to cloudwego to help users.❤️

**Comment by Duslia** [comment]
+1 Welcome~

**Comment by FGYFFFF** [comment]
+1 Welcome~

**Comment by GuangmingLuo** [comment]
+1 Welcome

**Comment by welkeyever** [comment]
Good job! Welcome~

**Comment by chaoranz758** [comment]
+1 Welcome

**Comment by baiyutang** [comment]
+1👍🏻

**Comment by GuangmingLuo** [comment]
Hi, your request has been reviewed by the CloudWeGo Hertz management team and passed with majority approval. Congratulations !

You have been invited to join [CloudWeGo](https://github.com/cloudwego) org and [hertz-contrib](https://github.com/hertz-contrib) org as a public member, as well as [Hertz](https://github.com/cloudwego/hertz) Committer Team in CloudWeGo. Your certificate is [here](https://github.com/cloudwego/community/blob/main/Committer/ViolaPioggia.pdf).

Please check [Responsibilities and privileges](https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md#responsibilities-and-privileges-1) for more details.

Welcome to Join us !
