### ISSUE TITLE
REQUEST: New membership for tksky1

### ISSUE THREAD

**Issue by tksky1** [cloudwego/community#79]
### GitHub Username

@tksky1

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md)
- [x] I have joined to the [Slack Channel](https://join.slack.com/t/cloudwego/shared_invite/zt-tmcbzewn-UjXMF3ZQsPhl7W3tEDZboA) and Feishu Group Chat (for Chinese)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more CloudWeGo repositories

### List of contributions to CloudWeGo

- thriftgo
  -  Feature
      -  https://github.com/cloudwego/thriftgo/pull/118
      - https://github.com/cloudwego/thriftgo/pull/121
      - https://github.com/cloudwego/thriftgo/pull/124
      - https://github.com/cloudwego/thriftgo/pull/131
      - https://github.com/cloudwego/thriftgo/pull/136
      -  https://github.com/cloudwego/thriftgo/pull/139
  -  Fix
      - https://github.com/cloudwego/thriftgo/pull/134
      - https://github.com/cloudwego/thriftgo/pull/133
      - https://github.com/cloudwego/thriftgo/pull/128
      - https://github.com/cloudwego/thriftgo/pull/127
- cloudwego.github.io
    - Doc
        - https://github.com/cloudwego/cloudwego.github.io/pull/849

**Comment by HeyJavaBean** [comment]
+1, support. @tksky1  is the developer of thriftgo IDL trimmer, and he has completed the entire project mainly by himself. This feature is very significant as it makes thriftgo more flexible and streamlined in terms of code generation. Additionally, it serves as an open bypass capability for all thrift users. Furthermore, after completing the development of the core functionality, he continuously incorporated user feedback to optimize and improve this project. He also plays a crucial role in maintaining the trimmer. I'm grateful for his contributions and hope he stays involved in Cloudwego's open-source projects.

**Comment by GuangmingLuo** [comment]
+ support

**Comment by felix021** [comment]
+1 support.

IDL Trimmer is very pratical to user.

**Comment by YangruiEmma** [comment]
Thanks for your contribution on idl trimming. Support!

**Comment by GuangmingLuo** [comment]
Hi, your request has been reviewed by the CloudWeGo management team and passed with majority approval. Congratulations !

You have been invited to join [CloudWeGo](https://github.com/cloudwego) org as a public member, as well as Serdes Committer Team in CloudWeGo. Your certificate is [here](https://github.com/cloudwego/community/blob/main/Committer/tksky1.pdf).

Please check [Responsibilities and privileges](https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md#responsibilities-and-privileges-1) for more details.

Welcome to Join us !
