### ISSUE TITLE
REQUEST: New membership for <baiyutang>

### ISSUE THREAD

**Issue by baiyutang** [cloudwego/community#8]
### GitHub Username

baiyutang

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md)
- [x] I have joined to the [Slack Channel](https://join.slack.com/t/cloudwego/shared_invite/zt-tmcbzewn-UjXMF3ZQsPhl7W3tEDZboA) and Feishu Group Chat (for Chinese)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more CloudWeGo repositories

### List of contributions to CloudWeGo

- PRs reviewed / authored
 1. [Finish it & merge into main repository  [kitex-contrib/registry-nacos]](https://github.com/kitex-contrib/registry-nacos/pull/1)
 2. [fix #115 [cloudwego.github.io]](https://github.com/cloudwego/cloudwego.github.io/pull/93)
 3. [基本特性增加锚点 [cloudwego.github.io]](https://github.com/cloudwego/cloudwego.github.io/pull/92)
 4. [错别字纠正 [cloudwego.github.io]](https://github.com/cloudwego/cloudwego.github.io/pull/90)
 5. [add a new networking lib [awesome-go]](https://github.com/avelino/awesome-go/pull/3869)
 6. [git action [registry-etcd]](https://github.com/kitex-contrib/registry-etcd/pull/3)
 7. [update the server ip as 127.0.0.1 [kitex-examples]](https://github.com/cloudwego/kitex-examples/pull/16)
 
- Blog
 1. [[ Kitex 源码解析] 函数式编程](https://xie.infoq.cn/article/0f98581b39d6ef5fe6977e6a6)
 2. [如何给 CloudWeGo 做贡献](https://xie.infoq.cn/article/74694e3a601ddae83249ba341)
 3. [[ CloudWeGo 微服务实践] Nacos 服务发现扩展 (1)](https://xie.infoq.cn/article/7abdda8804c1e3c5d70cba9c0)
 4. [[ CloudWeGo 微服务实践] Nacos 服务发现扩展 (2)](https://xie.infoq.cn/article/bd6c6bf8bdf4835fed29f4b56)

**Comment by GuangmingLuo** [comment]
baiyutang participates in the CloudWeGo community actively including the new extension of registry, doc optimization, and  evangelism. I agree with this request.

**Comment by bengol** [comment]
+1

**Comment by YangruiEmma** [comment]
I agree with @baiyutang's request, thank you for your contribution!

**Comment by GuangmingLuo** [comment]
Hi, your request has been reviewed by the project management team and passed with a comfortable majority. Congratulations !

You have been invited to join CloudWeGo and kitex-contrib orgs as public members.

Your certificate for being a member of our community is [here](https://github.com/cloudwego/community/blob/main/Committer/baiyutang.pdf).

Welcome to Join us !
