### ISSUE TITLE
REQUEST: New membership for <Lvnszn>

### ISSUE THREAD

**Issue by Lvnszn** [cloudwego/community#81]
### GitHub Username

lvnszn

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md)
- [x] I have joined to the [Slack Channel](https://join.slack.com/t/cloudwego/shared_invite/zt-tmcbzewn-UjXMF3ZQsPhl7W3tEDZboA) and Feishu Group Chat (for Chinese)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more CloudWeGo repositories

### List of contributions to CloudWeGo

- Issue
https://github.com/kitex-contrib/codec-dubbo/issues/37
https://github.com/cloudwego/kitex/issues/372

- Feature
https://github.com/cloudwego/kitex/pull/506
https://github.com/cloudwego/kitex/pull/528
https://github.com/cloudwego/kitex/pull/1076
https://github.com/cloudwego/kitex/pull/1168
https://github.com/cloudwego/kitex/pull/1169
https://github.com/kitex-contrib/codec-dubbo/pull/56
https://github.com/kitex-contrib/codec-dubbo/pull/33
https://github.com/cloudwego/thriftgo/pull/113

**Comment by felix021** [comment]
+1 support

@Lvnszn actively participated in the dubbo interoperability project and implemented the scaffold generation task. Meanwhile, he also fixed some other issues of Kitex.

**Comment by GuangmingLuo** [comment]
+1 support

**Comment by rogerogers** [comment]
+1 support

**Comment by baiyutang** [comment]
+1

**Comment by HeyJavaBean** [comment]
+1 support

@Lvnszn participated in the Kitex-Dubbo project and made significant contributions in the code generation tool.

**Comment by YangruiEmma** [comment]
+1 support

**Comment by GuangmingLuo** [comment]
Hi, your request has been reviewed by the CloudWeGo community management team and passed with majority approval. Congratulations !

You have been invited to join [CloudWeGo](https://github.com/cloudwego) org and [kitex-contrib](https://github.com/kitex-contrib) as a public member, as well as [Kitex](https://github.com/cloudwego/kitex) Committer Team in CloudWeGo. Your certificate is [here](https://github.com/cloudwego/community/blob/main/Committer/Lvnszn.pdf).

Please check [Responsibilities and privileges](https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md#responsibilities-and-privileges-1) for more details.

Welcome to Join us !
