### ISSUE TITLE
REQUEST: New Reviewer for <chaoranz758>

### ISSUE THREAD

**Issue by chaoranz758** [cloudwego/community#83]
### GitHub Username

chaoranz758

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md)
- [x] I have joined to the [Slack Channel](https://join.slack.com/t/cloudwego/shared_invite/zt-tmcbzewn-UjXMF3ZQsPhl7W3tEDZboA) and Feishu Group Chat (for Chinese)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more CloudWeGo repositories

### List of contributions to CloudWeGo

- PRs reviewed / authored
  - cwgo
    - https://github.com/cloudwego/cwgo/pull/83
    - https://github.com/cloudwego/cwgo/pull/84
    - https://github.com/cloudwego/cwgo/pull/85
    - https://github.com/cloudwego/cwgo/pull/86
    - https://github.com/cloudwego/cwgo/pull/87
    - https://github.com/cloudwego/cwgo/pull/88
    - https://github.com/cloudwego/cwgo/pull/89
    - https://github.com/cloudwego/cwgo/pull/90
    - https://github.com/cloudwego/cwgo/pull/91
    - https://github.com/cloudwego/cwgo/pull/92
    - https://github.com/cloudwego/cwgo/pull/97
    - https://github.com/cloudwego/cwgo/pull/98
    - https://github.com/cloudwego/cwgo/pull/99
    - https://github.com/cloudwego/cwgo/pull/94
  - hertz 
    - https://github.com/hertz-contrib/gzip/pull/11
    - https://github.com/hertz-contrib/gzip/pull/12
    - https://github.com/hertz-contrib/registry/pull/91
    - https://github.com/hertz-contrib/cache/pull/6
    - https://github.com/cloudwego/hertz/pull/972
  - website
    - https://github.com/cloudwego/cloudwego.github.io/pull/783
    - https://github.com/cloudwego/cloudwego.github.io/pull/791
    - https://github.com/cloudwego/cloudwego.github.io/pull/787
    - https://github.com/cloudwego/cloudwego.github.io/pull/795
    - https://github.com/cloudwego/cloudwego.github.io/pull/698
    - https://github.com/cloudwego/cloudwego.github.io/pull/819
    - https://github.com/cloudwego/cloudwego.github.io/pull/829
    - https://github.com/cloudwego/cloudwego.github.io/pull/807
    - https://github.com/cloudwego/cloudwego.github.io/pull/809
    - https://github.com/cloudwego/cloudwego.github.io/pull/856
- Issues responded to
  - https://github.com/cloudwego/hertz/issues/953
  - https://github.com/cloudwego/hertz/issues/973
  - https://github.com/cloudwego/hertz/issues/974
  - https://github.com/kitex-contrib/registry-etcd/issues/30
  - https://github.com/cloudwego/cloudwego.github.io/issues/802
  - https://github.com/cloudwego/cloudwego.github.io/issues/846
- 飞书文档
  - https://gd3idijo21.feishu.cn/docx/Hv2udUxluoTjtVxvZtKcnq8NnXd?from=from_copylink
  - https://gd3idijo21.feishu.cn/docx/DOL9dNdHEo60nhx6EaYcQiqNnzb?from=from_copylink
  - https://gd3idijo21.feishu.cn/docx/TKtidkmJLoahP7xaiHkcXPYXnyf?from=from_copylink
  - https://gd3idijo21.feishu.cn/docx/WwdTdmqsAob8dxxwCL7clcMmnAf?from=from_copylink

**Comment by li-jin-gou** [comment]
+1  @chaoranz758  Thank you for contributing to hertz and cwgo, hopefully with your help the cwgo tools will be released and help more users. ❤️

**Comment by welkeyever** [comment]
+1, welcome~

**Comment by rogerogers** [comment]
+1 support

**Comment by Duslia** [comment]
+1 welcome~

**Comment by GuangmingLuo** [comment]
+1   support

**Comment by GuangmingLuo** [comment]
Hi, your request has been reviewed by the CloudWeGo Hertz maintainer team and passed with majority approval.

You have been promoted as a member of [Hertz Reviewer](https://github.com/orgs/cloudwego/teams/hertz) Team in CloudWeGo. Your certificate is [here](https://github.com/cloudwego/community/blob/main/Reviewer/luruichao.pdf).

Please check [Responsibilities and privileges](https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md#responsibilities-and-privileges-2) for more details.

Congratulations !
