### ISSUE TITLE
REQUEST: New membership for <ahaostudy>

### ISSUE THREAD

**Issue by ahaostudy** [cloudwego/community#84]
### GitHub Username

ahaostudy

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md)
- [x] I have joined to the [Slack Channel](https://join.slack.com/t/cloudwego/shared_invite/zt-tmcbzewn-UjXMF3ZQsPhl7W3tEDZboA) and Feishu Group Chat (for Chinese)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more CloudWeGo repositories

### List of contributions to CloudWeGo

- codec-dubbo
https://github.com/kitex-contrib/codec-dubbo/pull/54
https://github.com/kitex-contrib/codec-dubbo/pull/58
https://github.com/kitex-contrib/codec-dubbo/pull/61
https://github.com/kitex-contrib/codec-dubbo/pull/62
https://github.com/kitex-contrib/codec-dubbo/pull/65
https://github.com/kitex-contrib/codec-dubbo/pull/68
https://github.com/kitex-contrib/codec-dubbo/pull/70

- kitex
https://github.com/cloudwego/kitex/pull/1137
https://github.com/cloudwego/kitex/pull/1167

**Comment by HeyJavaBean** [comment]
+1 support.

**Comment by YangruiEmma** [comment]
+1 support.
@ahaostudy is very actively involved in community projects

**Comment by GuangmingLuo** [comment]
+1 support

**Comment by DMwangnima** [comment]
+1 support

**Comment by Lvnszn** [comment]
+1 support

**Comment by li-jin-gou** [comment]
+1 ❤️

**Comment by whalecold** [comment]
+1 support

**Comment by tksky1** [comment]
+1 support

**Comment by GuangmingLuo** [comment]
Hi, your request has been reviewed by the CloudWeGo community management team and passed with majority approval. Congratulations !

You have been invited to join [CloudWeGo](https://github.com/cloudwego) org and [kitex-contrib](https://github.com/kitex-contrib) as a public member, as well as [Kitex](https://github.com/cloudwego/kitex) Committer Team in CloudWeGo. Your certificate is [here](https://github.com/cloudwego/community/blob/main/Committer/ahao.pdf).

Please check [Responsibilities and privileges](https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md#responsibilities-and-privileges-1) for more details.

Welcome to Join us !
