### ISSUE TITLE
REQUEST: New membership for <StellarisW>

### ISSUE THREAD

**Issue by StellarisW** [cloudwego/community#86]
### GitHub Username

StellarisW

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md)
- [x] I have joined to the [Slack Channel](https://join.slack.com/t/cloudwego/shared_invite/zt-tmcbzewn-UjXMF3ZQsPhl7W3tEDZboA) and Feishu Group Chat (for Chinese)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more CloudWeGo repositories

### List of contributions to CloudWeGo

- PRs reviewed / authored
  Cwgo:
  - https://github.com/cloudwego/cwgo/pull/80
  - https://github.com/cloudwego/cwgo/pull/33
  - https://github.com/cloudwego/hertz/pull/575

  Hertz:
  - https://github.com/hertz-contrib/logger/pull/27
  - https://github.com/hertz-contrib/casbin/pull/3
  - https://github.com/hertz-contrib/casbin/pull/2
  - https://github.com/hertz-contrib/logger/pull/19
  - https://github.com/hertz-contrib/websocket/pull/13
  
  Kitex:
  - https://github.com/cloudwego/kitex/pull/799
  
  docs:
  - https://github.com/cloudwego/cloudwego.github.io/pull/716
  - https://github.com/cloudwego/cloudwego.github.io/pull/526
  - https://github.com/cloudwego/cwgo/pull/32
  - https://github.com/cloudwego/hertz-examples/pull/76
  - https://github.com/cloudwego/volo/pull/126

**Comment by li-jin-gou** [comment]
Thank you for your contribution to cwgo.

**Comment by li-jin-gou** [comment]
+1 ❤️  Thank you very much for your contribution, I hope you can make the cwgo platform better and help more users.

**Comment by FGYFFFF** [comment]
+1 ❤️ Thank you very much for your contribution~~

**Comment by Duslia** [comment]
+1 Welcome

**Comment by rogerogers** [comment]
+1 Welcome

**Comment by ViolaPioggia** [comment]
+1 Welcome

**Comment by felix021** [comment]
+1 support. Expecting more kitex contribution from you [bisou]

**Comment by Lvnszn** [comment]
+1 support

**Comment by GuangmingLuo** [comment]
+ support

**Comment by GuangmingLuo** [comment]
Hi, your request has been reviewed by the CloudWeGo community management team and passed with majority approval. Congratulations !

You have been invited to join [CloudWeGo](https://github.com/cloudwego) org and [hertz-contrib](https://github.com/hertz-contrib) as a public member, as well as [Hertz](https://github.com/cloudwego/hertz) Committer Team in CloudWeGo. Your certificate is [here](https://github.com/cloudwego/community/blob/main/Committer/StellarisW.pdf).

Please check [Responsibilities and privileges](https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md#responsibilities-and-privileges-1) for more details.

Welcome to Join us !
