### ISSUE TITLE
REQUEST: New membership for Haswf

### ISSUE THREAD

**Issue by Haswf** [cloudwego/community#88]
### GitHub Username

@Haswf

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md)
- [x] I have joined to the [Slack Channel](https://join.slack.com/t/cloudwego/shared_invite/zt-tmcbzewn-UjXMF3ZQsPhl7W3tEDZboA) and Feishu Group Chat (for Chinese)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more CloudWeGo repositories

#### PRs reviewed / authored
- https://github.com/cloudwego/hertz/pull/1048
- https://github.com/cloudwego/hertz/pull/1041
- https://github.com/cloudwego/hertz/pull/284
- https://github.com/cloudwego/cloudwego.github.io/pull/929
- https://github.com/cloudwego/cloudwego.github.io/pull/209
- https://github.com/cloudwego/cloudwego.github.io/pull/259
- https://github.com/cloudwego/cloudwego.github.io/pull/266
- https://github.com/cloudwego/cloudwego.github.io/pull/931
- https://github.com/cloudwego/cloudwego.github.io/pull/592
- https://github.com/hertz-contrib/registry/pull/16
- https://github.com/hertz-contrib/sse/pull/1
- https://github.com/hertz-contrib/requestid/pull/1

#### Issues Authored
- https://github.com/cloudwego/hertz/issues/156
- https://github.com/cloudwego/hertz/issues/652
- https://github.com/cloudwego/hertz/issues/195
- https://github.com/cloudwego/hertz/issues/185
- https://github.com/cloudwego/hertz/issues/709
- https://github.com/cloudwego/cloudwego.github.io/issues/606

#### Issues responded to
- https://github.com/cloudwego/hertz/issues/1032
- https://github.com/cloudwego/hertz/issues/688
- https://github.com/cloudwego/hertz/issues/230
- https://github.com/cloudwego/hertz/issues/197

Looking back on my journey with CloudWeGo, I began by translating documentation into English for Hertz. Later, I migrated Gin middlewares for Hertz. As ChatGPT gained popularity, I had the opportunity to work on Server-Sent Events. With the introduction of Chrome's restrictions on third-party cookies, I added support for Partitioned Cookies, making Hertz the first Go web framework to adopt this new standard.

Contributing to open source projects is both fun and rewarding. I never imagined that my code would serve thousands of users worldwide. I would like to express my sincere appreciation to @welkeyever, @GuangmingLuo, @kingo, @Duslia, and all the individuals who supported me throughout this incredible journey. Thank you.

**Comment by li-jin-gou** [comment]
Thank you for your contribution, some good  first issues that you did not participate in but commented on can be deleted.

**Comment by li-jin-gou** [comment]
+1 ❤️

**Comment by FGYFFFF** [comment]
+1 , welcome❤️

**Comment by GuangmingLuo** [comment]
+1 support

**Comment by welkeyever** [comment]
+1, welldone!

**Comment by rogerogers** [comment]
+1 support

**Comment by CoderPoet** [comment]
+1 support

**Comment by Duslia** [comment]
+1 Welcome!

**Comment by GuangmingLuo** [comment]
Hi, your request has been reviewed by the CloudWeGo community management team and passed with majority approval. Congratulations !

You have been invited to join [CloudWeGo](https://github.com/cloudwego) org and [hertz-contrib](https://github.com/hertz-contrib) as a public member, as well as [Hertz](https://github.com/cloudwego/hertz) Committer Team in CloudWeGo. Your certificate is [here](https://github.com/cloudwego/community/blob/main/Committer/Haswf.pdf).

Please check [Responsibilities and privileges](https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md#responsibilities-and-privileges-1) for more details.

Welcome to Join us !

**Comment by Haswf** [comment]
> Hi, your request has been reviewed by the CloudWeGo community management team and passed with majority approval. Congratulations !
> 
> You have been invited to join [CloudWeGo](https://github.com/cloudwego) org and [hertz-contrib](https://github.com/hertz-contrib) as a public member, as well as [Hertz](https://github.com/cloudwego/hertz) Committer Team in CloudWeGo. Your certificate is [here](https://github.com/cloudwego/community/blob/main/Committer/Haswf.pdf).
> 
> Please check [Responsibilities and privileges](https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md#responsibilities-and-privileges-1) for more details.
> 
> Welcome to Join us !

Thank you. Looking forward to learn and thrive with the community together.
