### ISSUE TITLE
REQUEST: New membership for <cqqqq777>

### ISSUE THREAD

**Issue by cqqqq777** [cloudwego/community#92]
### GitHub Username

@cqqqq777 

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md)
- [x] I have joined to the [Slack Channel](https://join.slack.com/t/cloudwego/shared_invite/zt-tmcbzewn-UjXMF3ZQsPhl7W3tEDZboA) and Feishu Group Chat (for Chinese)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more CloudWeGo repositories

### List of contributions to CloudWeGo

- PRs reviewed / authored
doc:
https://github.com/cloudwego/cloudwego.github.io/pull/594
https://github.com/cloudwego/cloudwego.github.io/pull/612
https://github.com/cloudwego/cloudwego.github.io/pull/659
https://github.com/cloudwego/cloudwego.github.io/pull/720
https://github.com/cloudwego/hertz/pull/954
https://github.com/cloudwego/cloudwego.github.io/pull/868
https://github.com/cloudwego/cloudwego.github.io/pull/908
https://github.com/cloudwego/cloudwego.github.io/pull/921
https://github.com/cloudwego/cloudwego.github.io/pull/930
https://github.com/cloudwego/cloudwego.github.io/pull/937
https://github.com/cloudwego/cloudwego.github.io/pull/941
https://github.com/cloudwego/cloudwego.github.io/pull/957
https://github.com/cloudwego/cloudwego.github.io/pull/965
https://github.com/cloudwego/cloudwego.github.io/pull/970
https://github.com/cloudwego/cloudwego.github.io/pull/1023
https://github.com/cloudwego/cloudwego.github.io/pull/1038
https://github.com/cloudwego/kitex-examples/pull/118
https://github.com/cloudwego/cloudwego.github.io/pull/1047

review:
https://github.com/cloudwego/cloudwego.github.io/pull/1043
https://github.com/cloudwego/cloudwego.github.io/pull/889
https://github.com/cloudwego/cloudwego.github.io/pull/896
https://github.com/cloudwego/cloudwego.github.io/pull/901
https://github.com/cloudwego/cloudwego.github.io/pull/904

hertz:
https://github.com/cloudwego/hertz/pull/776

kitex-example:
https://github.com/cloudwego/kitex-examples/pull/105

hertz-example:
https://github.com/cloudwego/hertz-examples/pull/89

meeting:
https://github.com/cloudwego/community/pull/70
https://github.com/cloudwego/community/pull/72
https://github.com/cloudwego/community/pull/75
https://github.com/cloudwego/community/pull/85

- Issues responded to
https://github.com/cloudwego/kitex/issues/1223
https://github.com/cloudwego/kitex/issues/1224

**Comment by GuangmingLuo** [comment]
+1 support

**Comment by YangruiEmma** [comment]
Thank you for your contribution~ support!

**Comment by AsterDY** [comment]
@cqqqq777 is nice and hard-working. Support !

**Comment by rogerogers** [comment]
+1 support

**Comment by GuangmingLuo** [comment]
Hi, your request has been reviewed by the CloudWeGo community management team and passed with majority approval. Congratulations !

You have been invited to join [CloudWeGo](https://github.com/cloudwego) org as a public member, as well as Web&Docs Committer Team in CloudWeGo. Your certificate is [here](https://github.com/cloudwego/community/blob/main/Committer/cqqqq777.pdf).

Please check [Responsibilities and privileges](https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md#responsibilities-and-privileges-1) for more details.

Welcome to Join us !
