### ISSUE TITLE
REQUEST: New Reviewer for <whalecold>

### ISSUE THREAD

**Issue by whalecold** [cloudwego/community#94]
> Change `Membership` to `Commiter\Reviewer\Approver` in the title in your case.

### GitHub Username

whalecold

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md)
- [x] I have joined to the [Discord](https://discord.gg/jceZSE7DsW) and Feishu Group Chat (for Chinese)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more CloudWeGo repositories for more than 1 month

### List of contributions to CloudWeGo
- PRs reviewed / authored
  - xds
    - https://github.com/kitex-contrib/xds/pull/21
    - https://github.com/kitex-contrib/xds/pull/22
    - https://github.com/kitex-contrib/xds/pull/23
    - https://github.com/kitex-contrib/xds/pull/24
    - https://github.com/kitex-contrib/xds/pull/25
    - https://github.com/kitex-contrib/xds/pull/29
    - https://github.com/kitex-contrib/xds/pull/30
    - https://github.com/kitex-contrib/xds/pull/31
    - https://github.com/kitex-contrib/xds/pull/33
    - https://github.com/kitex-contrib/xds/pull/34
  - codec-dubbo
    - https://github.com/kitex-contrib/codec-dubbo/pull/92
  - codec-dubbo-tests
     - https://github.com/kitex-contrib/codec-dubbo-tests/pull/12
  - registry-nacos
    - https://github.com/kitex-contrib/registry-nacos/pull/32
    - https://github.com/kitex-contrib/registry-nacos/pull/26
    - https://github.com/kitex-contrib/registry-nacos/pull/25
  - config-nacos
    - https://github.com/kitex-contrib/config-nacos/pull/1
    - https://github.com/kitex-contrib/config-nacos/pull/2
    - https://github.com/kitex-contrib/config-nacos/pull/3
    - https://github.com/kitex-contrib/config-nacos/pull/4
    - https://github.com/kitex-contrib/config-nacos/pull/6
    - https://github.com/kitex-contrib/config-nacos/pull/8
    - https://github.com/kitex-contrib/config-nacos/pull/10
    - https://github.com/kitex-contrib/config-nacos/pull/11
    - https://github.com/kitex-contrib/config-nacos/pull/12
    - https://github.com/kitex-contrib/config-nacos/pull/15
    - https://github.com/kitex-contrib/config-nacos/pull/16
    - https://github.com/kitex-contrib/config-nacos/pull/17
    - https://github.com/kitex-contrib/config-nacos/pull/18
    - https://github.com/kitex-contrib/config-nacos/pull/19
    - https://github.com/kitex-contrib/config-nacos/pull/21
  - logger
    - https://github.com/hertz-contrib/logger/pull/22
  - kitex
    - https://github.com/cloudwego/kitex/pull/1035
    - https://github.com/cloudwego/kitex/pull/1038
    - https://github.com/cloudwego/kitex/pull/1048
    - https://github.com/cloudwego/kitex/pull/1058
    - https://github.com/cloudwego/kitex/pull/1083
    - https://github.com/cloudwego/kitex/pull/1363
   - protoc-gen-validator
     - https://github.com/cloudwego/protoc-gen-validator/pull/10
   - doc
     - https://github.com/cloudwego/cloudwego.github.io/pull/1126
     - https://github.com/cloudwego/cloudwego.github.io/pull/944
     - https://github.com/cloudwego/cloudwego.github.io/pull/896
     - https://github.com/cloudwego/cloudwego.github.io/pull/576
   - kitex-examples
     - https://github.com/cloudwego/kitex-examples/pull/131

- Issues responded to
  - https://github.com/cloudwego/kitex/issues/1042

**Comment by GuangmingLuo** [comment]
+ 1 strong support

**Comment by ppzqh** [comment]
+1 thanks @whalecold for your great contribution to cloudwego!

**Comment by jayantxie** [comment]
+1

**Comment by CoderPoet** [comment]
+1 thanks @whalecold for your great contribution to cloudwego!

**Comment by DMwangnima** [comment]
+1 Look up to you~

**Comment by YangruiEmma** [comment]
Support! Thanks for your great contribution to cloudwego!

**Comment by GuangmingLuo** [comment]
Hi @whalecold , your request has been reviewed by the CloudWeGo Kitex maintainer team and passed with majority approval.

You have been promoted as a CloudWeGo Kitex Reviewer. Your certificate is [here](https://github.com/cloudwego/community/blob/main/Reviewer/whalecold.pdf).

Please check [Responsibilities and privileges](https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md#responsibilities-and-privileges-2) for more details.

Congratulations !
