### ISSUE TITLE
REQUEST: New Commiter for <khan-yin>

### ISSUE THREAD

**Issue by khan-yin** [cloudwego/community#95]
> Change `Membership` to `Commiter\Reviewer\Approver` in the title in your case.

### GitHub Username

khan-yin

### Requirements

- [x] I have reviewed the community membership guidelines (https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md)
- [x] I have joined to the [Discord](https://discord.gg/jceZSE7DsW) and Feishu Group Chat (for Chinese)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more CloudWeGo repositories for more than 1 month

### List of contributions to CloudWeGo

- PRs reviewed / authored
https://github.com/cloudwego/dynamicgo/pull/30
https://github.com/cloudwego/dynamicgo/pull/37 **(main contributions, 37,820+ lines code containing main codebase and benchmark test)**
https://github.com/cloudwego/community/pull/85 **(join the meeting for sharing my contributions on dynamicgo)**
https://github.com/cloudwego/dynamicgo/pull/57
https://github.com/cloudwego/kitex/pull/1395
https://github.com/cloudwego/dynamicgo/pull/78

- Issues responded to
**Hope to continue to follow and participate in community discussions and contributions :)**
- Docs
[DynamicGo For Protobuf Protocol](https://github.com/cloudwego/dynamicgo/blob/main/proto/INTRODUCTION.md)
[CloudWeGo微信公众号-Dynamicgo 支持 Protobuf 动态反射](https://mp.weixin.qq.com/s/OeQwlgZJtYOGTHnN50IdOA)

**Comment by AsterDY** [comment]
+1

**Comment by GuangmingLuo** [comment]
+1 for dynamicgo committer

**Comment by Marina-Sakai** [comment]
+1

**Comment by YangruiEmma** [comment]
https://github.com/cloudwego/dynamicgo/blob/main/proto/INTRODUCTION.md  Your drawing is very good~
Thanks for contribution for dynamicgo!
Support it!

**Comment by GuangmingLuo** [comment]
Hi, your request has been reviewed by the CloudWeGo community management team and passed with majority approval as a Dynamicgo committer. Congratulations !

You have been invited to join [CloudWeGo](https://github.com/cloudwego) org as a public member. Your certificate is [here](https://github.com/cloudwego/community/blob/main/Committer/khan-yin.pdf).

Please check [Responsibilities and privileges](https://github.com/cloudwego/community/blob/main/COMMUNITY_MEMBERSHIP.md#responsibilities-and-privileges-1) for more details.

Welcome to Join us !

**Comment by khan-yin** [comment]
Thanks a lot!
